 <?php
	echo Tag::getDocumentTitle();
  	echo Tag::stylesheetLink('style');
    echo Tag::stylesheetlink('adminiziolite/reset',true);
	echo Tag::stylesheetlink('adminiziolite/main',true);
	echo Tag::stylesheetlink('adminiziolite/2col',true);
	//echo Tag::stylesheetlink('adminiziolite/1col',true);
	echo Tag::stylesheetlink('adminiziolite/style',true);
	echo Tag::stylesheetlink('adminiziolite/mystyle',true);
	echo Tag::stylesheetlink('menu_drop_down/styles',true);
	echo Tag::stylesheetlink('menu_drop_down/styles_h1',true);
	//echo Tag::stylesheetLinkTags();
  ?>
<style>
#accordion-resizer {
	padding: 5px;
	width: 250px;
	height: 100px;
}
</style>