<div id="dialogo_mensajes"   ></div>

<div id="dialogo_ies"   ></div>

<div id="dialogo_pais"   ></div>

<div id="dialogo_role"   ></div>

<div id="dialogo_nbc"   ></div>

<div id="dialogo_tipo_proyecto"   ></div>

<div id="dialogo_tipo_productos_de_investigacion"   ></div>

<div id="dialogo_grupos_de_investigacion"   ></div>

<div id="dialogo_objetivo_socioeconomico" ></div>

<div id="dialogo_centros_de_investigacion" ></div>

<div id="dialogo_productos_de_investigacion" ></div>

<div id="dialogo_redes_de_cooperacion" ></div>

<div id="dialogo_departamentos"  ></div>

<div id="dialogo_municipios"  ></div>

<div id="dialogo_fuentes_de_financiacion_nacional"  ></div>

<div id="dialogo_fuentes_de_financiacion_internacional"  ></div>

<div id="dialogo_tipos_de_gastos"  ></div>

<div id="dialogo_tipo_participacion_proyecto"  ></div>

<div id="dialogo_nivel_educativo"  ></div>

<div id="dialogo_sector_entidad"  ></div>

<div id="dialogo_entidades_integrantes_de_red"  ></div>

<div id="dialogo_investigadores"  ></div>

<div id="dialogo_rubros"  ></div>

<div id="dialogo_proyecto_de_investigacion"  ></div>



