<table id="tablaentidinred"></table>
<div id="pagerentidadintred"></div>
<script>
jQuery(document).ready(function(){

		
		jQuery("#tablaentidinred").jqGrid(
		{ 
			ajaxGridOptions : {type:"POST"},
			url:'<?php echo core::getInstancePath().Router::getController(); ?>/find_detalle_buscar', 
			datatype: "json", 
			colNames:['Codigo Entidad Integrante Red','Nombre Entidad Integrante Red'], 
			colModel:[ 
				{ name:'codigo_entidades_integrantes_red',index:'codigo_entidades_integrantes_red', width:200}, 
				{ name:'nombre_entidades_integrantes_red',index:'nombre_entidades_integrantes_red', width:350}
			], 
			autoWidth:true,
			width: 550,
			height: 250,
			rowNum:50, 
			/*rowList:[10,20,30,40,50], */
			pager: '#pagerentidadintred', 
			sortname: 'id', 
			/*shrinkToFit :false,*/
			viewrecords: true, 
			sortorder: "asc", 
			caption:"listado de los Entidad Integrante Red Registrados",
			ondblClickRow:function(rowid,iRow,iCol,e){
				
				var fila = jQuery(this).jqGrid('getRowData',rowid);
					
					if( jQuery("#codigo_entidades_integrantes_red")    ){ jQuery("#codigo_entidades_integrantes_red").val(fila['codigo_entidades_integrantes_red']); }
					if( jQuery("#nombre_entidades_integrantes_red") ){ jQuery("#nombre_entidades_integrantes_red").val(fila['nombre_entidades_integrantes_red']); } 
					
					jQuery("#dialogo_entidades_integrantes_de_red").dialog("close");											
       		 }
		}); 
		/*jQuery("#tablaentidinred").jqGrid('navGrid','#pagerentidadintred',{edit:false,add:false,del:false}); 
		jQuery("#tablaentidinred").jqGrid('navButtonAdd','#pagerentidadintred',{
		caption: "Columnas",
		title: "Reordena Columnas",
		onClickButton : function (){
			jQuery("#stablaentidinred").jqGrid('columnChooser');
		
	});}*/
});
</script>