<?php echo Tag::formRemote(Router::getController()."/update", "update: mensajes", "id: fx","name: fx"); ?>

<h1>MODIFICAR <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?></h1>

<table width="100%">
    	<tr>
    	  <th height="25" colspan="4">FORMULARIO PARA MODIFICAR <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?></th>
   	  </tr>
    	<tr>
    	  
    	  <th width="30%" align="right">CODIGO <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?>:</th>
    	  <td width="64%" align="left"><?php  echo Tag::textField("codigo_entidades_integrantes_red","size: 50","maxlength: 50"); ?></td>
    	  
   	  </tr>
      <tr>
    	  
    	  <th width="30%" align="right">NOMBRE <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?>:</th>
    	  <td width="64%" align="left"><?php  echo Tag::textField("nombre_entidades_integrantes_red","size: 50","maxlength: 50"); ?></td>
    	  
   	  </tr>
        <tr>
    	  
    	  <th width="30%" align="right">FECHA CREACION <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?>:</th>
    	  <td width="64%" align="left"><?php  echo Tag::textField("fecha_creacion","size: 20","maxlength: 50","readonly: readonly","value: ".date("Y-m-d")); ?></td>
    	  
   	  </tr>
      
      <tr>
    	  
    	  <th width="30%" align="right">FECHA RETIRO <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?>:</th>
    	  <td width="64%" align="left"><?php  echo Tag::textField("fecha_retiro","size: 20","maxlength: 50","readonly: readonly","value: ".date("Y-m-d")); ?></td>
    	  
   	  </tr>
        
        
        <tr>
    	  
    	  <th width="30%" align="right">PAIS:</th>
    	  <td width="64%" align="left">
		  		<?php  echo Tag::textField("codigo_pais","size: 10","maxlength: 50","readonly: readonly"); ?>
                <?php  echo Tag::textField("nombre_pais","size: 50","maxlength: 50","readonly: readonly"); ?>
                <button id="buscar_pais" name="buscar_pais" type="button">Buscar</button>
                </td>
    	  
   	  </tr>
      <tr>
    	  
    	  <th width="30%" align="right">SECTOR ENTIDAD:</th>
    	  <td width="64%" align="left">
		  	<?php  echo Tag::textField("codigo_sector_entidad","size: 10","maxlength: 50","readonly: readonly"); ?>
            <?php  echo Tag::textField("nombre_sector_entidad","size: 50","maxlength: 50","readonly: readonly"); ?>
            	<button id="buscar_sector_entidad" name="buscar_sector_entidad" type="button">Buscar</button>
            </td>
    	  
   	  </tr>
       
      <tr>
    	  <td colspan="4" align="center"><button id="guardar" name="guardar">Modificar Datos</button></td>
   	  </tr>
  </table>

<?php echo Tag::endForm(); ?>
<div id="mensajes"></div>
<?php echo view::getContent(); ?>

<script>
	
	
	jQuery(document).ready(function(e) {
        jQuery("#codigo_entidades_integrantes_red").attr("readOnly","ReadOnly");
		jQuery("#codigo_entidades_integrantes_red").css("background-color","#333");
    });
</script>