<table id="tablaroles"></table>
<div id="pagerroles"></div>
<script>
jQuery(document).ready(function(){

		
		jQuery("#tablaroles").jqGrid(
		{ 
			ajaxGridOptions : {type:"POST"},
			url:'<?php echo core::getInstancePath().Router::getController(); ?>/find_detalle_buscar', 
			datatype: "json", 
			colNames:['Codigo Role','Nombre Role'], 
			colModel:[ 
				{ name:'codigo_role',index:'codigo_role', width:200}, 
				{ name:'nombre_role',index:'nombre_role', width:350}
			], 
			autoWidth:true,
			width: 550,
			height: 250,
			rowNum:50, 
			/*rowList:[10,20,30,40,50], */
			pager: '#pagerroles', 
			sortname: 'id', 
			/*shrinkToFit :false,*/
			viewrecords: true, 
			sortorder: "asc", 
			caption:"listado de los Roles Registrados",
			ondblClickRow:function(rowid,iRow,iCol,e){
				
				var fila = jQuery(this).jqGrid('getRowData',rowid);
					
					if( jQuery("#codigo_role")    ){ jQuery("#codigo_role").val(fila['codigo_role']); }
					if( jQuery("#nombre_role") ){ jQuery("#nombre_role").val(fila['nombre_role']); } 
					
					
					
					
					jQuery("#dialogo_role").dialog("close");											
       		 }
		}); 
		/*jQuery("#tablaroles").jqGrid('navGrid','#pagerroles',{edit:false,add:false,del:false}); 
		jQuery("#tablaroles").jqGrid('navButtonAdd','#pagerroles',{
		caption: "Columnas",
		title: "Reordena Columnas",
		onClickButton : function (){
			jQuery("#stablaroles").jqGrid('columnChooser');
		
	});}*/
});
</script>