<?php echo Tag::formRemote(Router::getController()."/delete", "update: mensajes", "id: fx","name: fx"); ?>

<h1>ELIMINAR <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?></h1>

<table width="100%">
    	<tr>
    	  <th height="25" colspan="4">FORMULARIO PARA ELIMINAR <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?></th>
   	  </tr>
    	<tr>
    	  
    	  <th width="30%" align="right">CODIGO <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?>:</th>
    	  <td width="64%" align="left"><?php  echo Tag::textField("codigo_grupo_investigacion","size: 50","maxlength: 50"); ?></td>
    	  
   	  </tr>
        <tr>
    	  
    	  <th width="30%" align="right">NOMBRE <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?>:</th>
    	  <td width="64%" align="left"><?php  echo Tag::textField("nombre_grupo_investigacion","size: 50"); ?></td>
    	  
   	  </tr>
      	<tr>
    	  
    	  <th width="30%" align="right">FECHA CREACION <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?>:</th>
    	  <td width="64%" align="left"><?php  echo Tag::textField("fecha_creacion","size: 20","maxlength: 10"); ?></td>
    	  
   	  </tr>
        <tr>
    	  
    	  <th width="30%" align="right">FECHA VIGENCIA <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?>:</th>
    	  <td width="64%" align="left"><?php  echo Tag::textField("fecha_vigencia","size: 20","maxlength: 10"); ?></td>
    	  
   	  </tr>
      	<tr>
    	  
    	  <th width="30%" align="right">CODIGO IES:</th>
    	  <td width="64%" align="left">
		  		<?php  echo Tag::textField("cod_ies","size: 20","maxlength: 50","readonly: readonly"); ?>
                <?php  echo Tag::textField("nombre_ies","size: 50","maxlength: 50","readonly: readonly"); ?>
                <button id="buscar_ies" name="buscar_ies" type="button">Buscar</button>
          </td>
    	  
   	  </tr>
        <tr>
    	  
    	  <th width="30%" align="right">CODIGO NBC:</th>
    	  <td width="64%" align="left">
		  		<?php  echo Tag::textField("codigo_nbc","size: 20","maxlength: 50","readonly: readonly"); ?>
                <?php  echo Tag::textField("nombre_nbc","size: 50","maxlength: 50","readonly: readonly"); ?>
 				<button id="buscar_nbc" name="buscar_nbc" type="button">Buscar</button>
          </td>
    	  
   	  </tr>
      <tr>
    	  <td colspan="4" align="center"><button id="guardar" name="guardar">Eliminar</button></td>
   	  </tr>
  </table>

<?php echo Tag::endForm(); ?>
<div id="mensajes"></div>
<?php echo view::getContent(); ?>

<script>
	
	
	jQuery(document).ready(function(e) {
        jQuery("#codigo_grupo_investigacion").attr("readOnly","ReadOnly");
		jQuery("#nombre_grupo_investigacion").attr("readOnly","ReadOnly");
		jQuery("#fecha_creacion").attr("readOnly","ReadOnly");
		jQuery("#fecha_vigencia").attr("readOnly","ReadOnly");
		jQuery("#buscar_ies").attr("disabled","disabled");
		jQuery("#buscar_nbc").attr("disabled","disabled");
		

		//jQuery("#cod_ies").css("background-color","#333");
    });
</script>