<?php 
// require_once 'Classes/PHPExcel.php';
$objPHPExcel = new PHPExcel();

//Informacion del excel
$objPHPExcel->
getProperties()
	->setCreator("Proyecto Sies")
	->setLastModifiedBy("Proyecto Sies")
	->setTitle("Exportar excel desde Proyecto Sies")
	->setSubject("Proyecto Sies")
	->setDescription("Documento generado de Proyecto Sies")
	->setKeywords("Proyecto Sies")
	->setCategory("reportes");    

 

/*detallejson json*/
/*$filter = new Filter();
$detallejson = $filter->apply($_POST["detalles"], array("Striptags")); 
$detallejson = str_replace("]\"","]",str_replace("\"[","[",str_replace("\\","",$detallejson)));

if($detallejson!='[]'){	
	if(json_decode($detallejson)){
		//Flash::success("Json Correcto: detallejson");
		$detallejson = json_decode($detallejson);*/
		
$styleArray = array(
	'font' => array(
		'bold' => true,
	),
	'alignment' => array(
		'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
	),
	'borders' => array(
		'allborders' => array(
			'style' => PHPExcel_Style_Border::BORDER_THIN,
			'color' => array('argb' => 'FF9900')
		),
	),
	'fill' => array(
		'type' => PHPExcel_Style_Fill::FILL_SOLID,
		'rotation' => 90,
		'startcolor' => array(
			'argb' => 'FF9900',
		),
		'endcolor' => array(
			'argb' => 'FF9900',
		),
	),
);
     

$i=1;
$objPHPExcel->setActiveSheetIndex(0)->mergeCells("H1:O1");
$objPHPExcel->setActiveSheetIndex(0)->mergeCells("P1:W1");

$objPHPExcel->setActiveSheetIndex(0)->setCellValue("H1", "INTEGRANTES DEL GRUPO: INVESTIGADORES DE LA IES");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("P1", "INTEGRANTES DEL GRUPO: INVESTIGADORES EXTERNOS A LA IES");

$objPHPExcel->getActiveSheet()->getStyle('C1')->applyFromArray($styleArray);		
$objPHPExcel->getActiveSheet()->getStyle('H1')->applyFromArray($styleArray);		

$i=2;	

$objPHPExcel->setActiveSheetIndex(0)->setCellValue("A".$i, "CÓDIGO IES");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("B".$i, "NOMBRE IES");	
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("C".$i, "CÓDIGO DEL GRUPO");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("D".$i, "NOMBRE DEL GRUPO");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("E".$i, "NBC");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("F".$i, "FECHA DE CONFORMACIÓN DEL GRUPO");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("G".$i, "FECHA DE VIGENCIA DEL GRUPO");


$objPHPExcel->setActiveSheetIndex(0)->setCellValue("H".$i, "TIPO DE IDENTIFICACIÓN");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("I".$i, "NÚMERO DE IDENTIFICACIÓN");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("J".$i, "PRIMER NOMBRE");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("K".$i, "SEGUNDO NOMBRE");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("L".$i, "PRIMER APELLIDO");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("M".$i, "SEGUNDO APELLIDO");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("N".$i, "TIPO PARTICIPACIÓN EN EL GRUPO");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("O".$i, "NBC");

$objPHPExcel->setActiveSheetIndex(0)->setCellValue("P".$i, "TIPO DE IDENTIFICACIÓN");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("Q".$i, "NÚMERO DE IDENTIFICACIÓN");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("R".$i, "PRIMER NOMBRE");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("S".$i, "SEGUNDO NOMBRE");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("T".$i, "PRIMER APELLIDO");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("U".$i, "SEGUNDO APELLIDO");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("V".$i, "TIPO PARTICIPACIÓN EN EL GRUPO");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("W".$i, "NBC");



$objPHPExcel->getActiveSheet()->getStyle('A2:J2')->applyFromArray($styleArray);	


//$db = DbBase::rawConnect();
$i=3;

$ies  = new TblIes();
$cinv = new TblCentrosInvestigacion();
$grupos = new TblGruposInvCentrosInv();
$gruposenc = new TblGrupoInvestigacion();
$dpto = new TblDepartamento();
$mun  = new TblMunicipio();

$condicion_ies = "";
if($_REQUEST["cod_ies"]!=''){ $condicion_ies = $_REQUEST["cod_ies"]; }

foreach($ies->find(" 1 = 1 $condicion_ies ") as $ies):
	$objPHPExcel->setActiveSheetIndex(0)->setCellValue("A".$i, $ies->getCodIES());
	$objPHPExcel->setActiveSheetIndex(0)->setCellValue("B".$i, ($ies->getNombreIES()));
	$i++;
	foreach($cinv->find(" FK_Cod_IES = '".$ies->getCodIES()."' ") as $cinv):
		
		$objPHPExcel->setActiveSheetIndex(0)->setCellValue("C".$i, $cinv->getCodCentroInvestigacion());
		$objPHPExcel->setActiveSheetIndex(0)->setCellValue("D".$i, $cinv->getNombreCentroInvestigacion());
		
		$mun->findFirst("Cod_Municipio = '".$cinv->getFKCodMunicipio()."' ");
		$dpto->findFirst("Cod_Departamento = '".$mun->getFKCodDepartamento()."' ");
		
		$objPHPExcel->setActiveSheetIndex(0)->setCellValue("E".$i, $dpto->getDepartamento());
		$objPHPExcel->setActiveSheetIndex(0)->setCellValue("F".$i, $mun->getMunicipio());
		$objPHPExcel->setActiveSheetIndex(0)->setCellValue("G".$i, $cinv->getFechaCreacionCentroInvestigacion());
		foreach($grupos->find(" Cod_Centro_Inv = '".$cinv->getCodCentroInvestigacion()."' ") as $grupos):		
			$gruposenc->findFirst(" Cod_Grupo = '".$grupos->getCodGrupoInv()."' ");
			$objPHPExcel->setActiveSheetIndex(0)->setCellValue("H".$i, $gruposenc->Nombre_Grupo());
			$objPHPExcel->setActiveSheetIndex(0)->setCellValue("I".$i, $gruposenc->getFechaCreacionGrupoI());
			$objPHPExcel->setActiveSheetIndex(0)->setCellValue("J".$i, $gruposenc->getFechaVigenciaGrupoI());
		endforeach;	
	endforeach; //fin centros de investigacion
endforeach; //fin ies

$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('F')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('H')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('I')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('J')->setAutoSize('true');



header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="reportes.xlsx"');
header('Cache-Control: max-age=0');
 
$objWriter=PHPExcel_IOFactory::createWriter($objPHPExcel,'Excel2007');
$objWriter->save('php://output');
exit;





?>