<?php 
// require_once 'Classes/PHPExcel.php';
$objPHPExcel = new PHPExcel();

//Informacion del excel
$objPHPExcel->
getProperties()
	->setCreator("Proyecto Sies")
	->setLastModifiedBy("Proyecto Sies")
	->setTitle("Exportar excel desde Proyecto Sies")
	->setSubject("Proyecto Sies")
	->setDescription("Documento generado de Proyecto Sies")
	->setKeywords("Proyecto Sies")
	->setCategory("reportes");    

 

/*detallejson json*/
/*$filter = new Filter();
$detallejson = $filter->apply($_POST["detalles"], array("Striptags")); 
$detallejson = str_replace("]\"","]",str_replace("\"[","[",str_replace("\\","",$detallejson)));

if($detallejson!='[]'){	
	if(json_decode($detallejson)){
		//Flash::success("Json Correcto: detallejson");
		$detallejson = json_decode($detallejson);*/
		
$styleArray = array(
	'font' => array(
		'bold' => true,
	),
	'alignment' => array(
		'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
	),
	'borders' => array(
		'allborders' => array(
			'style' => PHPExcel_Style_Border::BORDER_THIN,
			'color' => array('argb' => 'FF9900')
		),
	),
	'fill' => array(
		'type' => PHPExcel_Style_Fill::FILL_SOLID,
		'rotation' => 90,
		'startcolor' => array(
			'argb' => 'FF9900',
		),
		'endcolor' => array(
			'argb' => 'FF9900',
		),
	),
);
     

$i=1;
$objPHPExcel->setActiveSheetIndex(0)->mergeCells("H1:O1");
$objPHPExcel->setActiveSheetIndex(0)->mergeCells("P1:W1");

$objPHPExcel->setActiveSheetIndex(0)->setCellValue("H1", "INTEGRANTES DEL GRUPO: INVESTIGADORES DE LA IES");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("P1", "INTEGRANTES DEL GRUPO: INVESTIGADORES EXTERNOS A LA IES");

$objPHPExcel->getActiveSheet()->getStyle('H1')->applyFromArray($styleArray);		
$objPHPExcel->getActiveSheet()->getStyle('P1')->applyFromArray($styleArray);		

$i=2;	

$objPHPExcel->setActiveSheetIndex(0)->setCellValue("A".$i, "CÓDIGO IES");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("B".$i, "NOMBRE IES");	
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("C".$i, "CÓDIGO DEL GRUPO");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("D".$i, "NOMBRE DEL GRUPO");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("E".$i, "NBC");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("F".$i, "FECHA DE CONFORMACIÓN DEL GRUPO");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("G".$i, "FECHA DE VIGENCIA DEL GRUPO");


$objPHPExcel->setActiveSheetIndex(0)->setCellValue("H".$i, "TIPO DE IDENTIFICACIÓN");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("I".$i, "NÚMERO DE IDENTIFICACIÓN");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("J".$i, "PRIMER NOMBRE");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("K".$i, "SEGUNDO NOMBRE");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("L".$i, "PRIMER APELLIDO");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("M".$i, "SEGUNDO APELLIDO");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("N".$i, "TIPO PARTICIPACIÓN EN EL GRUPO");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("O".$i, "NBC");

$objPHPExcel->setActiveSheetIndex(0)->setCellValue("P".$i, "TIPO DE IDENTIFICACIÓN");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("Q".$i, "NÚMERO DE IDENTIFICACIÓN");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("R".$i, "PRIMER NOMBRE");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("S".$i, "SEGUNDO NOMBRE");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("T".$i, "PRIMER APELLIDO");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("U".$i, "SEGUNDO APELLIDO");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("V".$i, "TIPO PARTICIPACIÓN EN EL GRUPO");
$objPHPExcel->setActiveSheetIndex(0)->setCellValue("W".$i, "NBC");



$objPHPExcel->getActiveSheet()->getStyle('A2:W2')->applyFromArray($styleArray);	


//$db = DbBase::rawConnect();
$i=3;

$ies  = new TblIes();
$nbc  = new TblNbc();
$grupos = new TblGrupoInvestigacion();
$gruposinv = new TblGrupoInvestigacionInvestigadores();
$gruposinvex = new TblGrupoInvestigacionInvestigadoresExternos();
$inv = new TblInvestigador();
$invex = new TblInvestigadorExterno();
$tp = new TblTipoParticipacionProyecto();

$dpto = new TblDepartamento();
$mun  = new TblMunicipio();

$condicion_ies = "";
$condicion_grupos = "";
if($_REQUEST["cod_ies"]!=''){ $condicion_ies = " and Cod_IES = '".$_REQUEST["cod_ies"]."' "; }

if($_REQUEST["desde"]!=''){ $condicion_grupos .= " and Fecha_Creacion_Grupo_I >= '".$_REQUEST["desde"]."' "; }

if($_REQUEST["hasta"]!=''){ $condicion_grupos .= " and Fecha_Vigencia_Grupo_I <= '".$_REQUEST["hasta"]."' "; }

foreach($ies->find(" 1 = 1 $condicion_ies ") as $ies):
	$objPHPExcel->setActiveSheetIndex(0)->setCellValue("A".$i, $ies->getCodIES());
	$objPHPExcel->setActiveSheetIndex(0)->setCellValue("B".$i, ($ies->getNombreIES()));
	
	foreach($grupos->find(" FK_Cod_IES = '".$ies->getCodIES()."' $condicion_grupos ") as $grupos):		
			
			$objPHPExcel->setActiveSheetIndex(0)->setCellValue("C".$i, $grupos->getCodGrupo());
			$objPHPExcel->setActiveSheetIndex(0)->setCellValue("D".$i, $grupos->getNombreGrupo());
			$nbc = $nbc->findFirst( " Cod_NBC = '".$grupos->getFKCodNBC()."' " );
			$objPHPExcel->setActiveSheetIndex(0)->setCellValue("E".$i, $nbc->getDescripcionNBC());
			$objPHPExcel->setActiveSheetIndex(0)->setCellValue("F".$i, $grupos->getFechaCreacionGrupoI());
			$objPHPExcel->setActiveSheetIndex(0)->setCellValue("G".$i, $grupos->getFechaVigenciaGrupoI());
			/*investigadores de la h a o*/
			$k=$i;
			foreach($gruposinv->find(" Cod_Grupo_Investigacion = '".$grupos->getCodGrupo()."' ") as $gruposinv):		
					$inv = $inv->findFirst( " Identificacion = '".$gruposinv->getIdentificacionInvestigador()."'" );
					$objPHPExcel->setActiveSheetIndex(0)->setCellValue("H".$k, $inv->getTipoIdentificacion());
					$objPHPExcel->setActiveSheetIndex(0)->setCellValue("I".$k, $inv->getIdentificacion());
					$objPHPExcel->setActiveSheetIndex(0)->setCellValue("J".$k, $inv->getPrimerNombre());
					$objPHPExcel->setActiveSheetIndex(0)->setCellValue("K".$k, $inv->getSegundoNombre());
					$objPHPExcel->setActiveSheetIndex(0)->setCellValue("L".$k, $inv->getPrimerApellido());
					$objPHPExcel->setActiveSheetIndex(0)->setCellValue("M".$k, $inv->getSegundoApellido());
					$nbc = $nbc->findFirst( " Cod_NBC = '".$inv->getFKCodNBC()."' " );
					$tp = $tp->findFirst( " Cod_Tipo_Participacion_Proyecto = '".$inv->getFKCodTipoParticipacionProyecto()."' " );
					$objPHPExcel->setActiveSheetIndex(0)->setCellValue("N".$k, $tp->getDescripcionTipoParticipacionProyecto());
					$objPHPExcel->setActiveSheetIndex(0)->setCellValue("O".$k, $nbc->getDescripcionNBC());
					$k++;
			endforeach;		
			$j=$i;
			/*investigadores de la p a w*/
			foreach($gruposinvex->find(" Cod_Grupo_Investigacion = '".$grupos->getCodGrupo()."' ") as $gruposinvex):		
					$invex = $invex->findFirst( " Identificacion_Externo = '".$gruposinvex->getIdentificacionInvestigador()."'" );
					$objPHPExcel->setActiveSheetIndex(0)->setCellValue("P".$j, $invex->getTipoIdentificacion());
					$objPHPExcel->setActiveSheetIndex(0)->setCellValue("Q".$j, $invex->getIdentificacion());
					$objPHPExcel->setActiveSheetIndex(0)->setCellValue("R".$j, $invex->getPrimerNombre());
					$objPHPExcel->setActiveSheetIndex(0)->setCellValue("S".$j, $invex->getSegundoNombre());
					$objPHPExcel->setActiveSheetIndex(0)->setCellValue("T".$j, $invex->getPrimerApellido());
					$objPHPExcel->setActiveSheetIndex(0)->setCellValue("U".$j, $invex->getSegundoApellido());
					$nbc = $nbc->findFirst( " Cod_NBC = '".$invex->getFKCodNBC()."' " );
					$tp = $tp->findFirst( " Cod_Tipo_Participacion_Proyecto = '".$invex->getFKCodTipoParticipacionProyecto()."' " );
					$objPHPExcel->setActiveSheetIndex(0)->setCellValue("V".$j, $tp->getDescripcionTipoParticipacionProyecto());
					$objPHPExcel->setActiveSheetIndex(0)->setCellValue("W".$j, $nbc->getDescripcionNBC());
					$j++;
			endforeach;		
			$i = $objPHPExcel->getActiveSheet()->getHighestRow()+1;	
	endforeach;	
		$i = $objPHPExcel->getActiveSheet()->getHighestRow() + 1;	
endforeach; //fin ies

$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('F')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('H')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('I')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('J')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('K')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('L')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('M')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('N')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('O')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('P')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('Q')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('R')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('S')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('T')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('U')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('V')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('W')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('X')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('Y')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('Z')->setAutoSize('true');
$objPHPExcel->getActiveSheet()->getColumnDimension('AA')->setAutoSize('true');




header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="reportes.xlsx"');
header('Cache-Control: max-age=0');
 
$objWriter=PHPExcel_IOFactory::createWriter($objPHPExcel,'Excel2007');
$objWriter->save('php://output');
exit;





?>