<?php echo Tag::form("reportes/excel_grupos_investigacion_ingenierias", "id: fx","name: fx","target: _blanck"); ?>
<table width="700px">
<tr>
  <td colspan="2" align="center">FILTROS</td>
</tr>
<tr>
	<td width="200" >CODIGO IES</td>
    <td>
		<?php  echo Tag::textField("cod_ies","size: 10","maxlength: 50","readonly: readonly"); ?>
        <?php  echo Tag::textField("nombre_ies","size: 50","maxlength: 50","readonly: readonly"); ?>
        <button type="button" id="buscar_ies" name="buscar_ies">Buscar</button>
    </td>
</tr>
<tr>
    	<td align="right">Fecha Creacion : </td>
      <td>Desde        <input type="text" id="desde" name="desde" />        Hasta: 
      <input type="text" id="hasta" name="hasta" /></td>
    </tr>
    

<tr>
	<td width="200">&nbsp;</td>
    <td>&nbsp;</td>
</tr>
</table>
<br />
<div align="center">
  <button  type="submit" id="guardar" name="guardar2">Exportar a Excel</button></div>
<br />

 <div align="center" id="progressbarWrapper" style="height:30px; width:100% " class="ui-widget-default">
    <div id="progressbar" style="height:100%;"></div>
 </div>
<br />

<?php echo Tag::endForm(); ?>

<script>

jQuery(document).ready(function(e) {
    jQuery("#fx").submit(function(e) {
       
		/*if(jQuery("#cod_ies").val()==''){
				
				jQuery("#dialogo_mensajes").html();
				jQuery("#dialogo_mensajes").html("Escoja una Ies. Ies es Requerida");
				jQuery("#dialogo_mensajes").dialog("open");
				return false;
			}else{*/
					jQuery("#fx").submit();
				/*	return false;
				}*/
    });
});

</script>