
 <h1>Reportes Proyecto de Investigacion</h1>   	

<table align="center" width="100%" border="1" cellspacing="2" cellpadding="2">

 

  <tr>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("reportes/proyecto",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("reportes/centros_investigacion",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("reportes/grupos_investigacion_ingenierias",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("reportes/investigadores_externos_ies",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

  </tr>

  <tr>

    <td height="30" align="center" valign="middle">Proyectos</td>

    <td height="30" align="center" valign="middle">Reporte Centros de Investigacion</td>

    <td height="30" align="center" valign="middle">Grupos Investigación Ingenierias</td>

    <td height="30" align="center" valign="middle">Investigadores Externos a la IES</td>

  </tr>
  
  <tr>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("reportes/otras_actividades",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("reportes/productos_investigacion",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("reportes/proyectos_investigacion_ingenierias",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("reportes/redes_cooperacion",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>
	
s
  </tr>

  <tr>
	
    <td height="30" align="center" valign="middle">Otras actividades</td>
 
    <td height="30" align="center" valign="middle">Productos de investigación</td>

    <td height="30" align="center" valign="middle">Proyectos de investigación_ingenierias</td>

    <td height="30" align="center" valign="middle">Redes de cooperación</td>



  </tr>
  <tr>
    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("reportes/flujo_de_caja",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>
    <td height="30" align="center" valign="middle">&nbsp;</td>
    <td height="30" align="center" valign="middle">&nbsp;</td>
    <td height="30" align="center" valign="middle">&nbsp;</td>
  </tr>
  <tr>
    <td align="center" valign="middle">Flujo de Caja</td>
    <td height="30" align="center" valign="middle">&nbsp;</td>
    <td height="30" align="center" valign="middle">&nbsp;</td>
    <td height="30" align="center" valign="middle">&nbsp;</td>
  </tr>
</table>
