<?php 
$page = $_REQUEST['page']; 
// get the requested page 
$limit = $_REQUEST['rows']; 
// get how many rows we want to have into the grid 
$sidx = $_REQUEST['sidx']; 
// get index row - i.e. user click to sort 
$sord = $_REQUEST['sord']; 
// get the direction if(!$sidx) 
//$sidx =1; 
if(!$sidx) $sidx =1;

$wh = "";
$searchOn = Strip($_REQUEST['_search']);
if($searchOn=='true') {
	$searchOper = $_REQUEST["searchOper"];
	$searchField = $_REQUEST["searchField"];
	$searchString = $_REQUEST["searchString"];
	
		switch ($searchOper) {
			case 'eq': $wh = " and $searchField = '$searchString' "; break;
		}
	
}

$condicion = "";
if(isset($_REQUES["desde"])){ if($_REQUES["desde"]!=''){ $condicion .= " and tbl_proyecto.Fecha_Inicio_Proyecto >= '".$_REQUES["desde"]."' "; } }
if(isset($_REQUES["hasta"])){ if($_REQUES["hasta"]!=''){ $condicion .= " and tbl_proyecto.Fecha_Inicio_Proyecto <= '".$_REQUES["hasta"]."' "; } }
if(isset($_REQUES["cod_ies"])){ if($_REQUES["cod_ies"]!=''){ $condicion .= " and tbl_ies.Cod_IES = '".$_REQUES["cod_ies"]."' "; } }
if(isset($_REQUES["cedula"])){ if($_REQUES["cedula"]!=''){ $condicion .= " and tbl_investigador.Identificacion = '".$_REQUES["cedula"]."' "; } }
$sq_nombre = "concat_ws(' ',tbl_investigador.PrimerNombre,tbl_investigador.SegundoNombre,tbl_investigador.PrimerApellido,tbl_investigador.SegundoApellido)";
if(isset($_REQUES["nombre"])){ if($_REQUES["nombre"]!=''){ $condicion .= " and $sq_nombre like '%".str_replace(' ','%',$_REQUES["nombre"])."%' "; } }

// connect to the database 
//$db = mysql_connect($dbhost, $dbuser, $dbpassword) or die("Connection Error: " . mysql_error()); 
//mysql_select_db($database) or die("Error conecting to db."); 

$db = DbBase::rawConnect();

$result = $db->query("SELECT COUNT(*) AS count 
							FROM (
								SELECT 
								  flujo_caja.id,
								  flujo_caja.Cod_Proyecto,
								  tbl_investigador.Identificacion,
								  tbl_investigador.PrimerNombre,
								  tbl_investigador.SegundoNombre,
								  tbl_investigador.PrimerApellido,
								  tbl_investigador.SegundoApellido,
								  tbl_proyecto.Titulo_Proyecto,
								  tbl_proyecto.Fecha_Inicio_Proyecto,
								  tbl_proyecto.Duracion_Proyecto,
								  tbl_proyecto.Valor_Proyecto,
								  tbl_ies.Cod_IES,
								  tbl_ies.Nombre_IES
								FROM
								  tbl_proyecto
								  INNER JOIN flujo_caja ON (tbl_proyecto.Cod_Proyecto = flujo_caja.Cod_Proyecto)
								  INNER JOIN tbl_investigador ON (flujo_caja.Identificacion = tbl_investigador.Identificacion)
								  INNER JOIN tbl_ies ON (tbl_proyecto.FK_Cod_IES = tbl_ies.Cod_IES)
							where 1=1
									$condicion	  
								  ) tb where 1 = 1 ".$wr); 

$row = $db->fetchArray($result); 

$count = $row['count']; 

if( $count >0 ) { 
		$total_pages = ceil($count/$limit); 
	} else { 
		$total_pages = 0; 
} 

if ($page > $total_pages) $page=$total_pages; 
	$start = $limit*$page - $limit;  // do not put 	$limit*($page - 1) 
	$responce = new stdClass();
	$SQL = "SELECT 
			   flujo_caja.id,
			  flujo_caja.Cod_Proyecto,
			  tbl_investigador.Identificacion,
			  CONCAT_WS(' ',tbl_investigador.PrimerNombre,
			  tbl_investigador.SegundoNombre,
			  tbl_investigador.PrimerApellido,
			  tbl_investigador.SegundoApellido ) as nombre,
			  tbl_proyecto.Titulo_Proyecto,
			  tbl_proyecto.Fecha_Inicio_Proyecto,
			  tbl_proyecto.Duracion_Proyecto,
			  tbl_proyecto.Valor_Proyecto,
			  tbl_ies.Cod_IES,
			  tbl_ies.Nombre_IES
			FROM
			  tbl_proyecto
			  INNER JOIN flujo_caja ON (tbl_proyecto.Cod_Proyecto = flujo_caja.Cod_Proyecto)
			  INNER JOIN tbl_investigador ON (flujo_caja.Identificacion = tbl_investigador.Identificacion)
			  INNER JOIN tbl_ies ON (tbl_proyecto.FK_Cod_IES = tbl_ies.Cod_IES)
			  
			where 1 = 1 
				$condicion	  
			".$wh."
			ORDER BY $sidx $sord 
			LIMIT $start , $limit"; 
	$result = $db->query( $SQL ); 
	$responce->page = $page ;
	$responce->sql = $SQL; 
	$responce->total = $total_pages; 
	$responce->records = $count; 
	$i=0; 
	while( $row = $db->fetchArray($result) ) { 
		$responce->rows[$i]['id']=$row[id]; 
		
		$responce->rows[$i]['cell']=array($row[id],$row[Cod_IES],$row[Nombre_IES],$row[Cod_Proyecto],$row[Titulo_Proyecto],$row[Fecha_Inicio_Proyecto],$row[Duracion_Proyecto],$row[Valor_Proyecto],$row[Identificacion],$row[nombre]); 
		$i++; 
	} 
	
	echo json_encode($responce);
		
		
function Strip($value)
{
	if(get_magic_quotes_gpc() != 0)
  	{
    	if(is_array($value))  
			if ( array_is_associative($value) )
			{
				foreach( $value as $k=>$v)
					$tmp_val[$k] = stripslashes($v);
				$value = $tmp_val; 
			}				
			else  
				for($j = 0; $j < sizeof($value); $j++)
        			$value[$j] = stripslashes($value[$j]);
		else
			$value = stripslashes($value);
	}
	return $value;
}

function array_is_associative ($array)
{
    if ( is_array($array) && ! empty($array) )
    {
        for ( $iterator = count($array) - 1; $iterator; $iterator-- )
        {
            if ( ! array_key_exists($iterator, $array) ) { return true; }
        }
        return ! array_key_exists(0, $array);
    }
    return false;
}

?>
