<?php 
	if(isset($_REQUEST["opcion"])){
		Flash::notice("Doble Click en la Fila para ".$_REQUEST["opcion"]); 
	}
?>
<table id="tabla<?php echo Router::getController(); ?>"></table>
<div id="pager<?php echo Router::getController(); ?>"></div>
<script>
jQuery(document).ready(function(){

		
		jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid(
		{ 
			ajaxGridOptions : {type:"POST"},
			url:'<?php echo core::getInstancePath().Router::getController(); ?>/find_detalle_buscar', 
			datatype: "json", 
			colNames:['Codigo Proyecto','Titulo','Fecha inicio',"Duracion","valor","Ies","Nombre Ies","Cod Tipo Proyecto","Nombre Tipo Proyecto"], 
			colModel:[ 
				{ name:'codigo_proyecto',index:'Cod_Proyecto', width:200}, 
				{ name:'titulo_proyecto',index:'Titulo_Proyecto', width:200},
				{ name:'fecha_inicio',index:'Fecha_Inicio_Proyecto', width:100}, 
				{ name:'duracion',index:'Duracion_Proyecto', width:100},
				{ name:'valor',index:'Valor_Proyecto', width:100},
				{ name:'codigo_ies',index:'Cod_IES', width:100},
				{ name:'nombre_ies',index:'Nombre_IES', width:100},
				{ name:'codigo_tipo_proyecto',index:'Cod_Tipo_Proyecto', width:100},
				{ name:'nombre_tipo_proyecto',index:'Descripcion_Tipo_Proyecto', width:100}
			], 
			autoWidth:true,
			width: 850,
			height: 250,
			rowNum:50, 
			/*rowList:[10,20,30,40,50], */
			pager: '#pager<?php echo Router::getController(); ?>', 
			sortname: 'Cod_Proyecto', 
			/*shrinkToFit :false,*/
			viewrecords: true, 
			sortorder: "asc", 
			caption:"listado de los Proyectos Registrados",
			ondblClickRow:function(rowid,iRow,iCol,e){
				
				var fila = jQuery(this).jqGrid('getRowData',rowid);
					
					if( jQuery("#codigo_proyecto")    ){ jQuery("#codigo_proyecto").val(fila['codigo_proyecto']); }
					if( jQuery("#titulo_proyecto") ){ jQuery("#titulo_proyecto").val(fila['titulo_proyecto']); } 
					
					<?php if(isset($_REQUEST["opcion"]) ){ ?>
						redireccionar_action("<?php echo Router::getController(); ?>/<?php echo $_REQUEST["opcion"]; ?>/" + fila['codigo_proyecto'] );
					<?php }else{?>	
						jQuery("#dialogo_<?php echo Router::getController(); ?>").dialog("close");
					<?php } ?>
					
       		 }
		}); 
		jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid('navGrid','#pager<?php echo Router::getController(); ?>',{edit:false,add:false,del:false}); 
			/*jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid('navButtonAdd','#pager<?php echo Router::getController(); ?>',{
			caption: "Columnas",
			title: "Reordena Columnas",
				onClickButton : function (){
					jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid('columnChooser');
				
				}
			}
		);*/
});
</script>