<?php 
$page = $_REQUEST['page']; 
// get the requested page 
$limit = $_REQUEST['rows']; 
// get how many rows we want to have into the grid 
$sidx = $_REQUEST['sidx']; 
// get index row - i.e. user click to sort 
$sord = $_REQUEST['sord']; 
// get the direction if(!$sidx) 
//$sidx =1; 
if(!$sidx) $sidx =1;

$wh = "";
$searchOn = Strip($_REQUEST['_search']);
if($searchOn=='true') {
	$searchOper = $_REQUEST["searchOper"];
	$searchField = $_REQUEST["searchField"];
	$searchString = $_REQUEST["searchString"];
	
		switch ($searchOper) {
			case 'eq': $wh = " and $searchField = '$searchString' "; break; //igual
			case 'ne': $wh = " and $searchField != '$searchString' "; break; // no igual
			case 'bn': $wh = " and $searchField not like  '$searchString%' "; break; //no empieza por
			case 'en': $wh = " and $searchField like '%$searchString' "; break; // no termina por
			case 'cn': $wh = " and $searchField like '%$searchString%' "; break; // no termina por
			case 'nc': $wh = " and $searchField not like '%$searchString%' "; break; //no contiene
			case 'in': $wh = " and $searchField in ($searchString) "; break; // esta en
			case 'ni': $wh = " and $searchField not in ($searchString) "; break; // no esta en
		}
	
}

// connect to the database 
//$db = mysql_connect($dbhost, $dbuser, $dbpassword) or die("Connection Error: " . mysql_error()); 
//mysql_select_db($database) or die("Error conecting to db."); 

$db = DbBase::rawConnect();

$result = $db->query("SELECT COUNT(*) AS count
											FROM
											  tbl_ies
											  INNER JOIN tbl_proyecto ON (tbl_ies.Cod_IES = tbl_proyecto.FK_Cod_IES)
											  INNER JOIN tbl_tipo_proyecto ON (tbl_proyecto.FK_Tipo_Proyecto = tbl_tipo_proyecto.Cod_Tipo_Proyecto)
								  where 1 = 1 ".$wr); 

$row = $db->fetchArray($result); 

$count = $row['count']; 

if( $count >0 ) { 
		$total_pages = ceil($count/$limit); 
	} else { 
		$total_pages = 0; 
} 

if ($page > $total_pages) $page=$total_pages; 
	$start = $limit*$page - $limit;  // do not put 	$limit*($page - 1) 
	$responce = new stdClass();
	$SQL = "SELECT  
			  tbl_proyecto.Cod_Proyecto,
			  tbl_proyecto.Titulo_Proyecto,
			  tbl_proyecto.Fecha_Inicio_Proyecto,
			  tbl_proyecto.Duracion_Proyecto,
			  tbl_proyecto.Valor_Proyecto,
			  tbl_ies.Cod_IES,
			  tbl_ies.Nombre_IES,
			  tbl_tipo_proyecto.Cod_Tipo_Proyecto,
			  tbl_tipo_proyecto.Descripcion_Tipo_Proyecto
			FROM
			  tbl_ies
			  INNER JOIN tbl_proyecto ON (tbl_ies.Cod_IES = tbl_proyecto.FK_Cod_IES)
			  INNER JOIN tbl_tipo_proyecto ON (tbl_proyecto.FK_Tipo_Proyecto = tbl_tipo_proyecto.Cod_Tipo_Proyecto)

			where 1 = 1 ".$wh."
			ORDER BY $sidx $sord 
			LIMIT $start , $limit"; 
	$result = $db->query( $SQL ); 
	$responce->page = $page ;
	$responce->sql = $SQL; 
	$responce->total = $total_pages; 
	$responce->records = $count; 
	$i=0; 
	while( $row = $db->fetchArray($result) ) { 
		$responce->rows[$i]['id']=$row[Cod_Proyecto]; 
		$responce->rows[$i]['cell']=array($row[Cod_Proyecto],utf8_encode($row[Titulo_Proyecto]),$row[Fecha_Inicio_Proyecto],$row[Duracion_Proyecto],$row[Valor_Proyecto],$row[Cod_IES],utf8_encode($row[Nombre_IES]),$row[Cod_Tipo_Proyecto],utf8_encode($row[Descripcion_Tipo_Proyecto])); 
		$i++; 
	} 
	
	echo json_encode($responce);
		
		
function Strip($value)
{
	if(get_magic_quotes_gpc() != 0)
  	{
    	if(is_array($value))  
			if ( array_is_associative($value) )
			{
				foreach( $value as $k=>$v)
					$tmp_val[$k] = stripslashes($v);
				$value = $tmp_val; 
			}				
			else  
				for($j = 0; $j < sizeof($value); $j++)
        			$value[$j] = stripslashes($value[$j]);
		else
			$value = stripslashes($value);
	}
	return $value;
}

function array_is_associative ($array)
{
    if ( is_array($array) && ! empty($array) )
    {
        for ( $iterator = count($array) - 1; $iterator; $iterator-- )
        {
            if ( ! array_key_exists($iterator, $array) ) { return true; }
        }
        return ! array_key_exists(0, $array);
    }
    return false;
}

?>
