<?php 
$page = $_REQUEST['page']; 
// get the requested page 
$limit = $_REQUEST['rows']; 
// get how many rows we want to have into the grid 
$sidx = $_REQUEST['sidx']; 
// get index row - i.e. user click to sort 
$sord = $_REQUEST['sord']; 
// get the direction if(!$sidx) 
//$sidx =1; 
if(!$sidx) $sidx =1;

$wh = "";
$searchOn = Strip($_REQUEST['_search']);
if($searchOn=='true') {
	$searchOper = $_REQUEST["searchOper"];
	$searchField = $_REQUEST["searchField"];
	$searchString = $_REQUEST["searchString"];
	
		switch ($searchOper) {
			case 'eq': $wh = " and $searchField = '$searchString' "; break;
		}
	
}

$condicion1= "";
if(isset($_REQUEST["codigo_departamentos"])){
		if($_REQUEST["codigo_departamentos"]!=''){ $condicion1 = " Cod_Departamento = ".$_REQUEST["codigo_departamentos"]; }
	}


// connect to the database 
//$db = mysql_connect($dbhost, $dbuser, $dbpassword) or die("Connection Error: " . mysql_error()); 
//mysql_select_db($database) or die("Error conecting to db."); 

$db = DbBase::rawConnect();

$result = $db->query("SELECT COUNT(*) AS count 
							FROM tbl_pais p, tbl_departamento d, tbl_municipio m 
							where 1 = 1 
							and p.Cod_Pais = d.FK_Cod_Pais
							and d.Cod_Departamento = m.FK_Cod_Departamento
							$condicion1
							".$wr); 

$row = $db->fetchArray($result); 

$count = $row['count']; 

if( $count >0 ) { 
		$total_pages = ceil($count/$limit); 
	} else { 
		$total_pages = 0; 
} 

if ($page > $total_pages) $page=$total_pages; 
	$start = $limit*$page - $limit;  // do not put 	$limit*($page - 1) 
	$responce = new stdClass();
	$SQL = "SELECT p.*,d.*,m.* 
					FROM tbl_pais p , tbl_departamento d, tbl_municipio m
			where 1 = 1 
			and p.Cod_Pais = d.FK_Cod_Pais
			and d.Cod_Departamento = m.FK_Cod_Departamento
			$condicion1
			".$wh."
			ORDER BY $sidx $sord 
			LIMIT $start , $limit"; 
	$result = $db->query( $SQL ); 
	$responce->page = $page ;
	$responce->sql = $SQL; 
	$responce->total = $total_pages; 
	$responce->records = $count; 
	$i=0; 
	while( $row = $db->fetchArray($result) ) { 
		$responce->rows[$i]['id']=$row[Cod_Municipio]; 
		$responce->rows[$i]['cell']=array($row[Cod_Municipio],utf8_encode($row[Municipio]),$row[Cod_Departamento],utf8_encode($row[Departamento]),$row[Cod_Pais],utf8_encode($row[Nombre_Pais])); 
		$i++; 
	} 
	
	echo json_encode($responce);
		
		
function Strip($value)
{
	if(get_magic_quotes_gpc() != 0)
  	{
    	if(is_array($value))  
			if ( array_is_associative($value) )
			{
				foreach( $value as $k=>$v)
					$tmp_val[$k] = stripslashes($v);
				$value = $tmp_val; 
			}				
			else  
				for($j = 0; $j < sizeof($value); $j++)
        			$value[$j] = stripslashes($value[$j]);
		else
			$value = stripslashes($value);
	}
	return $value;
}

function array_is_associative ($array)
{
    if ( is_array($array) && ! empty($array) )
    {
        for ( $iterator = count($array) - 1; $iterator; $iterator-- )
        {
            if ( ! array_key_exists($iterator, $array) ) { return true; }
        }
        return ! array_key_exists(0, $array);
    }
    return false;
}

?>
