<?php 
$path = $_SERVER['DOCUMENT_ROOT'].core::getInstancePath().'public/files/';
$path_system = $_SERVER['DOCUMENT_ROOT'];
$path_system = str_replace("htdocs","mysql/bin/",$path_system);

if (!empty($_REQUEST['filename'])) {
	// ahora validaremos y verificaremos las entradas
	// para saber lo que tenemos y abortar si hay algo mal
	$errors = array();
	$n = 0;
	/* pondremos cualquier error dentro de este array, y al final
	los listaremos todos para que los vea el usuario
	y pueda corregirlos */
	if (empty($_REQUEST['filename'])) { // no hay nombre de fichero
		$errors[$n] = "Debe introducir un nombre de fichero.";
		$n++;
	}
	 
	if (empty($_REQUEST['mysqluser'])) { // no hay usuario MySQL
		$errors[$n] = "Debe introducir un nombre de usuario MySQL.";
		$n++;
	}
	 
	/*if (empty($_REQUEST['mysqlpass'])) { // no hay password MySQL
		$errors[$n] = "Debe introducir un password MySQL .";
		$n++;
	}*/
	 
	// Ha seleccionado copiar una BD, pero no han dicho cual
	if ($_REQUEST['backupall'] == 'false' && empty($_REQUEST['backupwhichdb'])) {
	
		$errors[$n] = "Has selecciona copiar una base de datos, ".
		"pero no especificaste cual.";
		$n++;
	}
	
	//fin posibles errores del post	
}
 
if ($n > 0) {


	 // Si hubo errores en la fase de validacion...
	// muestra una pagina de error
	
	 
	?>
	
	<h1>Remote Database Backup</h1>
	<h2>No se pudo realizar la copia.</h2>
	<ul>
	
	<?php foreach ($errors as $err) { ?>
    <li>
		<?php echo $err; // y muestra su texto ?>
	</li>
	<?php }	?>
	</ul>
	 
	<a href="">	Volver al formulario de Backup</a>
	
<?php

}else{

 
// Si estamos aqui, es que se ha acabado bien la validación
// hacemos "escape shell" a los argumentos para evitar
// la inyección de código
// recuerda que esto es solo seguridad basica, se deberian
// añadir mas capas para mayor seguridad

$_REQUEST['filename'] = escapeshellcmd($_REQUEST['filename']);
$_REQUEST['mysqluser'] = escapeshellarg($_REQUEST['mysqluser']);
$_REQUEST['mysqlpass'] = escapeshellcmd($_REQUEST['mysqlpass']);
$_REQUEST['backupwhichdb']=escapeshellarg($_REQUEST['backupwhichdb']);
 
// Queremos copiar todas las bases de datos?
//$backupall = ($_REQUEST['backupall'] == 'false') ? false : true;
 
// Si queremos copiar todas, ponemos esto con -A en el comando,
// sino, lo ponemos con el nombre de la base de datos a copiar
$dbarg = $backupall ? '-A' : $_REQUEST['backupwhichdb'];
 
// formamos el comando a ejecutar
$command = "$path_system/mysqldump --extended-insert --comments=0 --disable-keys ".$dbarg." -a -u ".$_REQUEST['mysqluser']." -p".$_REQUEST['mysqlpass']."  -r \"".$path.$_REQUEST['filename']."\" 2>&1";
 
// creamos una cabecera y mostramos el progreso al usuario
// Podria tomar su tiempo

 
// execute the command we just set up
system($command);
 
// si eligieron comprimir con bzip, entonces se hace
if ($_REQUEST['bzip'] == 'true') {
	system('bzip2 "'.$path.$_REQUEST['filename'].'"');
}
 
// OK, terminamos. Digale al usuario lo que ha pasado.
// Si ocurrio algun error, se muestran en la llamada a system()
?>

<h2>Comando ejecutado. Si hubo errores, Se mostrarán arriba.</h2>

<?php echo View::renderPartial("listar_copias"); ?>

<script>ocultar();</script>

<?php } ?>

<?php echo View::getContent(); ?>