<table id="tablatipoproy"></table>
<div id="pagertipoproy"></div>
<script>
jQuery(document).ready(function(){

		
		jQuery("#tablatipoproy").jqGrid(
		{ 
			ajaxGridOptions : {type:"POST"},
			url:'<?php echo core::getInstancePath().Router::getController(); ?>/find_detalle_buscar', 
			datatype: "json", 
			colNames:['Codigo Tipo Producto Investigacion','Nombre Tipo Producto Investigacion'], 
			colModel:[ 
				{ name:'codigo_tipo_productos_de_investigacion',index:'codigo_tipo_productos_de_investigacion', width:200}, 
				{ name:'nombre_tipo_productos_de_investigacion',index:'nombre_tipo_productos_de_investigacion', width:350}
			], 
			autoWidth:true,
			width: 550,
			height: 250,
			rowNum:50, 
			/*rowList:[10,20,30,40,50], */
			pager: '#pagertipoproy', 
			sortname: 'id', 
			/*shrinkToFit :false,*/
			viewrecords: true, 
			sortorder: "asc", 
			caption:"listado de los Tipo Producto Investigacion Registrados",
			ondblClickRow:function(rowid,iRow,iCol,e){
				
				var fila = jQuery(this).jqGrid('getRowData',rowid);
					
					if( jQuery("#codigo_tipo_productos_de_investigacion")    ){ jQuery("#codigo_tipo_productos_de_investigacion").val(fila['codigo_tipo_productos_de_investigacion']); }
					if( jQuery("#nombre_tipo_productos_de_investigacion") ){ jQuery("#nombre_tipo_productos_de_investigacion").val(fila['nombre_tipo_productos_de_investigacion']); } 
					jQuery("#dialogo_tipo_productos_de_investigacion").dialog("close");											
       		 }
		}); 
		/*jQuery("#tablatipoproy").jqGrid('navGrid','#pagertipoproy',{edit:false,add:false,del:false}); 
		jQuery("#tablatipoproy").jqGrid('navButtonAdd','#pagertipoproy',{
		caption: "Columnas",
		title: "Reordena Columnas",
		onClickButton : function (){
			jQuery("#tablatipoproy").jqGrid('columnChooser');
		
	});}*/
});
</script>