<?php echo Tag::formRemote(Router::getController()."/delete", "update: mensajes", "id: fx","name: fx"); ?>

<h1>ELIMINAR <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?></h1>

<table width="100%">
    	<tr>
    	  <th height="25" colspan="4">FORMULARIO PARA ELIMINAR <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?></th>
   	  </tr>
    	<tr>
    	  
    	  <th width="30%" align="right">CODIGO <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?></th>
    	  <td width="64%" align="left"><?php  echo Tag::textField("codigo_sector_entidad","size: 50","maxlength: 50"); ?></td>
    	  
   	  </tr>
        <tr>
    	  
    	  <th width="30%" align="right">DESCRIPCION <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?></th>
    	  <td width="64%" align="left"><?php  echo Tag::textField("nombre_sector_entidad","size: 50"); ?></td>
    	  
   	  </tr>
        <tr>
    	  
    	  <th width="30%" align="right">CODIGO IES:</th>
    	  <td width="64%" align="left">
		  	<?php  echo Tag::textField("cod_ies","size: 10","maxlength: 50","readonly: readonly"); ?>
            <?php  echo Tag::textField("nombre_ies","size: 50","maxlength: 50","readonly: readonly"); ?>
            <button type="button" id="buscar_ies" name="buscar_ies">Buscar</button>
          </td>
    	  
   	  </tr>
       <tr>
    	  
    	  <th width="30%" align="right">PAIS:</th>
    	  <td width="64%" align="left">
          	<?php  echo Tag::textField("codigo_pais","size: 10","maxlength: 50","readonly: readonly"); ?>
          	<?php  echo Tag::textField("nombre_pais","size: 50","maxlength: 50","readonly: readonly"); ?>
          	
            <button id="buscar_pais" name="buscar_pais" type="button">Buscar</button>
          </td>
    	  
   	  </tr>
      <tr>
    	  <td colspan="4" align="center"><button id="guardar" name="guardar">Eliminar</button></td>
   	  </tr>
  </table>

<?php echo Tag::endForm(); ?>
<div id="mensajes"></div>
<?php echo view::getContent(); ?>

<script>
	
	
	jQuery(document).ready(function(e) {
        jQuery("#codigo_sector_entidad").attr("readOnly","ReadOnly");
		jQuery("#nombre_sector_entidad").attr("readOnly","ReadOnly");
		jQuery("#buscar_ies").attr("disabled","disabled");
		jQuery("#buscar_pais").attr("disabled","disabled");
		
		//jQuery("#cod_ies").css("background-color","#333");
    });
</script>