<?php 
$page = $_REQUEST['page']; 
// get the requested page 
$limit = $_REQUEST['rows']; 
// get how many rows we want to have into the grid 
$sidx = $_REQUEST['sidx']; 
// get index row - i.e. user click to sort 
$sord = $_REQUEST['sord']; 
// get the direction if(!$sidx) 
//$sidx =1; 
if(!$sidx) $sidx =1;

$wh = "";
$searchOn = Strip($_REQUEST['_search']);
if($searchOn=='true') {
	$searchOper = $_REQUEST["searchOper"];
	$searchField = $_REQUEST["searchField"];
	$searchString = $_REQUEST["searchString"];
	
		switch ($searchOper) {
			case 'eq': $wh = " and $searchField = '$searchString' "; break;
		}
	
}

// connect to the database 
//$db = mysql_connect($dbhost, $dbuser, $dbpassword) or die("Connection Error: " . mysql_error()); 
//mysql_select_db($database) or die("Error conecting to db."); 
/*
SELECT 
  sc.Cod_Sector_Entidad,
  sc.FK_Cod_IES,
  sc.FK_Cod_Pais,
  sc.Descripcion_Sector_Entidad,
  p.Cod_Pais,
  p.Nombre_Pais,
  i.Cod_IES,
  i.Nombre_IES
FROM
  tbl_sector_entidad sc,
  tbl_pais p,
  tbl_ies i
WHERE
  sc.FK_Cod_IES = i.Cod_IES AND 
  p.Cod_Pais = sc.FK_Cod_Pais*/
  
$condicion1= "";
if(isset($_REQUEST["cod_ies"])){
		if($_REQUEST["cod_ies"]!='' && $_REQUEST["cod_ies"]!='undefined'){ $condicion1 = " and  Cod_IES = ".$_REQUEST["cod_ies"]; }
	}
	
$condicion2= "";
if(isset($_REQUEST["codigo_pais"])){
		if($_REQUEST["codigo_pais"]!='' && $_REQUEST["codigo_pais"]!='undefined' ){ $condicion2 = " and  Cod_Pais = ".$_REQUEST["codigo_pais"]; }
	}	
	
$db = DbBase::rawConnect();

$result = $db->query("SELECT COUNT(*) AS count 
						FROM
							  tbl_sector_entidad sc,
							  tbl_pais p,
							  tbl_ies i
							where 
							1 = 1 
						      and sc.FK_Cod_IES = i.Cod_IES 
							  AND p.Cod_Pais = sc.FK_Cod_Pais
							  $condicion1
							  $condicion2
							".$wr); 

$row = $db->fetchArray($result); 

$count = $row['count']; 

if( $count >0 ) { 
		$total_pages = ceil($count/$limit); 
	} else { 
		$total_pages = 0; 
} 

if ($page > $total_pages) $page=$total_pages; 
	$start = $limit*$page - $limit;  // do not put 	$limit*($page - 1) 
	$responce = new stdClass();
	$SQL = "SELECT sc.Cod_Sector_Entidad,
				  sc.FK_Cod_IES,
				  sc.FK_Cod_Pais,
				  sc.Descripcion_Sector_Entidad,
				  p.Cod_Pais,
				  p.Nombre_Pais,
				  i.Cod_IES,
				  i.Nombre_IES 
					FROM
							  tbl_sector_entidad sc,
							  tbl_pais p,
							  tbl_ies i
							where 
							1 = 1 
						      and sc.FK_Cod_IES = i.Cod_IES 
							  AND p.Cod_Pais = sc.FK_Cod_Pais
							  $condicion1
							  $condicion2
							   ".$wh."
			ORDER BY $sidx $sord 
			LIMIT $start , $limit"; 
	$result = $db->query( $SQL ); 
	$responce->page = $page ;
	$responce->sql = $SQL; 
	$responce->total = $total_pages; 
	$responce->records = $count; 
	$i=0; 
	while( $row = $db->fetchArray($result) ) { 
		$responce->rows[$i]['id']=$row[Cod_Sector_Entidad]; 
		$responce->rows[$i]['cell']=array($row[Cod_Sector_Entidad],utf8_encode($row[Descripcion_Sector_Entidad]),$row[Cod_Pais],utf8_encode($row[Nombre_Pais]),$row[Cod_IES],utf8_encode($row[Nombre_IES])); 
		$i++; 
	} 
	
	echo json_encode($responce);
		
		
function Strip($value)
{
	if(get_magic_quotes_gpc() != 0)
  	{
    	if(is_array($value))  
			if ( array_is_associative($value) )
			{
				foreach( $value as $k=>$v)
					$tmp_val[$k] = stripslashes($v);
				$value = $tmp_val; 
			}				
			else  
				for($j = 0; $j < sizeof($value); $j++)
        			$value[$j] = stripslashes($value[$j]);
		else
			$value = stripslashes($value);
	}
	return $value;
}

function array_is_associative ($array)
{
    if ( is_array($array) && ! empty($array) )
    {
        for ( $iterator = count($array) - 1; $iterator; $iterator-- )
        {
            if ( ! array_key_exists($iterator, $array) ) { return true; }
        }
        return ! array_key_exists(0, $array);
    }
    return false;
}

?>
