<?php echo Tag::formRemote(Router::getController()."/delete", "update: mensajes", "id: fx","name: fx"); ?>

<h1>AGREGAR <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?></h1>

<table width="100%">
      <tr>
    	  <th height="25" colspan="4">FORMULARIO PARA AGREGAR <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?></th>
   	  </tr>
    	<tr>
    	  
    	  <th width="30%" align="right">CODIGO <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?>:</th>
    	  <td width="64%" align="left"><?php  echo Tag::textField("codigo_actividades_investigacion","size: 50","maxlength: 50"); ?></td>
    	  
   	  </tr>
      
        <tr>
    	  
    	  <th width="30%" align="right">NOMBRE <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?>:</th>
    	  <td width="64%" align="left"><?php  echo Tag::textField("nombre_actividades_investigacion","size: 50","maxlength: 50"); ?></td>
    	  
   	  </tr>
      
       <tr>
    	<th align="right">CODIGO IES</th>
        <th align="left"><?php  echo Tag::textField("cod_ies","size: 10","maxlength: 50","readonly: readonly"); ?>
          NOMBRE IES
<?php  echo Tag::textField("nombre_ies","size: 50","maxlength: 50","readonly: readonly"); ?>          <button type="button" id="buscar_ies" name="buscar_ies">Buscar</button></th>
    </tr>
      <tr>
    	  <th width="30%" align="right"  >AÑO</th>
    	  <td width="64%" align="left" ><?php  echo Tag::textField("annos","size: 6","maxlength: 4","value: ".date("Y"),"onkeyup: solonumeros(this);"); ?></td>
   	  </tr>
      <tr>
    	  <th width="30%" align="right" >SEMESTRE</th>
    	  <td width="64%" align="left" >
                <select id="semestre" name="semestre">
                    <option value="1">SEMESTRE 1</option>
                    <option value="2">SEMESTRE 2</option>
                </select>
          </td>
   	  </tr>
      
  </table>
  
  <h4>FUENTES DE FINANCIACION NACIONAL</h4>
<table id="tabla_fuentes_de_financiacion_nacional" width="900px">
	<tr>
    	<td width="200px">FUENTES DE FINANCIACION NACIONAL</td>
        <td colspan="3"><!--<button type="button" id="buscar_fuentes_de_financiacion_nacional">Buscar</button>--></td>
    </tr>
</table>
<table id="proyecto_fuentes_de_financiacion_nacional"> 
	<tbody>
        <tr id="pffn_encabezados" class="ui-dialog-titlebar ui-widget-header ui-corner-all">	
            <td width="200px">Codigo</td>
            <td colspan="2" width="450px">Nombre</td>
            <td width="200px">borrar</td>
        </tr>
        <?php 
	   		$fnac = new TblFuenteFinanciacionNacional();
	   		foreach($fnacional as $filas): ?> 
       <tr id="pffn_<?php echo $filas->getId(); ?>" >	
            <td width="200px"><?php echo $filas->getFKCodFuenteFNacional(); ?></td>
            <td colspan="2" width="450px"><?php echo utf8_encode($fnac->findFirst("  Cod_Fuente_Financiacion_Nacional = '".$filas->getFKCodFuenteFNacional()."' ")->getDescripcionFuenteFinanciacionNacional()); ?></td>
            <td width="200px">
            	<!--<button type="button" id='pffn_eliminar_<?php echo $filas->getId(); ?>' onClick='jQuery("#pffn_<?php echo $filas->getId(); ?>").remove();' >Borrar Fila</button> -->
            </td>
        </tr>
       <!-- <script>jQuery("#pffn_eliminar_<?php echo $filas->getId(); ?>").button({ icons: {primary:'ui-icon ui-icon-circle-minus' ,secondary:'ui-icon ui-icon-trash'} });</script>   -->      
       <?php endforeach;?>
    </tbody>
</table>
<h4>FUENTES DE FINANCIACION INTERNACIONAL</h4>
<table id="tabla_grupos_investigacion" width="900px">
	<tr>
    	<td width="200px">FUENTES DE FINANCIACION INTERNACIONAL</td>
        <td colspan="3"><!--<button type="button" id="buscar_fuentes_de_financiacion_internacional">Buscar</button>--></td>
    </tr>
</table>
<table id="proyecto_fuentes_de_financiacion_internacional"> 
	<tbody>
        <tr id="pffi_encabezados" class="ui-dialog-titlebar ui-widget-header ui-corner-all">	
            <td width="200px">Codigo</td>
            <td colspan="2" width="450px">Nombre</td>
            <td width="200px">borrar</td>
        </tr>
         <?php 
	   		$fnac = new TblFuenteFinanciacionInternacional();
	   		foreach($finternacional as $filas): ?> 
       <tr id="pffi_<?php echo $filas->getId(); ?>" >	
            <td width="200px"><?php echo $filas->getFKCodFuenteFInternacional(); ?></td>
            <td colspan="2" width="450px"><?php echo utf8_encode($fnac->findFirst(" Cod_Fuente_Financiacion_Internacional = '".$filas->getFKCodFuenteFInternacional()."' ")->getDescripcionFuenteFinanciacionInternacional()); ?></td>
            <td width="200px">
            	<!--<button type="button" id='pffi_eliminar_<?php echo $filas->getId(); ?>' onClick='jQuery("#pffi_<?php echo $filas->getId(); ?>").remove();' >Borrar Fila</button> -->
            </td>
        </tr>
       <!-- <script>jQuery("#pffi_eliminar_<?php echo $filas->getId(); ?>").button({ icons: {primary:'ui-icon ui-icon-circle-minus' ,secondary:'ui-icon ui-icon-trash'} });</script>        -->
       <?php endforeach;?>
    </tbody>
</table>
<h4>GASTOS</h4>
<table id="tabla_gastos" width="900px">
	<tr>
    	<td width="100px" align="left">TIPO DE GATOS</td>
        <td width="400px" align="left">
			<?php echo Tag::textField("codigo_tipo_de_gastos","size: 10","readonly: readonly"); ?>
            <?php echo Tag::textField("nombre_tipo_de_gastos","size: 40","readonly: readonly"); ?>
    		 <button type="button" id="buscar_tipos_de_gastos">Buscar</button>
        </td>
        <td width="100px" align="left">VALOR GASTO:</td>
        <td width="200px" align="left"><?php echo Tag::textField("valor_gastos","size: 30"); ?></td>
    </tr>
     
    <tr>
    	<td colspan="4">&nbsp;</td>
    </tr>
    <tr>
    	<td align="center" colspan="4"><button type="button" id="agregar_gasto" name="agregar_gasto">Agregar Gasto</button></td>
    </tr>
</table>
<table id="proyecto_gastos"> 
	<tbody>
        <tr id="pgastos_encabezados" class="ui-dialog-titlebar ui-widget-header ui-corner-all">	
            <td width="150px">Codigo</td>
            <td width="400px">Nombre</td>
            <td width="100px">Valor</td>
            <td width="150px">borrar</td>
        </tr>
        <?php 
	   		$fnac = new TblTipoGasto();
	   		foreach($gastos as $filas): ?> 
       		<tr id="pgastos_<?php echo $filas->getCodGasto(); ?>" >	
                <td><?php echo $filas->getFKCodTipoGastos(); ?></td>
                <td><?php echo utf8_encode($fnac->findFirst(" Cod_Tipo_Gasto = '".$filas->getFKCodTipoGastos()."' ")->getDescripcionTipoGasto()); ?></td>
                <td><?php echo $filas->getValorGastos(); ?></td>
                <td>
                    <!--<button type="button" id='pgastos_eliminar_<?php //echo $filas->getCodGasto(); ?>' onClick='jQuery("#pgastos_<?php //echo $filas->getCodGasto(); ?>").remove();' >Borrar Fila</button> -->
                </td>
        	</tr>
       <!-- <script>jQuery("#pgastos_eliminar_<?php echo $filas->getCodGasto(); ?>").button({ icons: {primary:'ui-icon ui-icon-circle-minus' ,secondary:'ui-icon ui-icon-trash'} });</script>  -->      
       <?php endforeach;?>
    </tbody>
</table>
<div align="center"><button  type="submit" id="guardar" name="guardar2">Eliminar Esta Actividad</button></div>
<?php echo Tag::endForm(); ?>

<?php echo view::getContent(); ?>
<br />

<br />
<div id="mensajes"></div>
<br />



<script>
jQuery(document).ready(function(e) {

	jQuery("#fx").find("input,textarea").attr("readolny","readonly");
	
	
});
</script>