<table id="tablapais"></table>
<div id="pagerpais"></div>
<script>
jQuery(document).ready(function(){

		
		jQuery("#tablapais").jqGrid(
		{ 
			ajaxGridOptions : {type:"POST"},
			url:'<?php echo core::getInstancePath().Router::getController(); ?>/find_detalle_buscar', 
			datatype: "json", 
			colNames:['Codigo Actividad Investigacion','Nombre Actividad Investigacion'], 
			colModel:[ 
				{ name:'codigo_actividades_investigacion',index:'Cod_Actividades_Investigacion', width:200}, 
				{ name:'nombre_actividades_investigacion',index:'Descripcion_Actividades_Investigacion', width:500}
			], 
			autoWidth:true,
			width: 550,
			height: 250,
			rowNum:50, 
			/*rowList:[10,20,30,40,50], */
			pager: '#pagerpais', 
			sortname: 'Cod_Actividades_Investigacion', 
			/*shrinkToFit :false,*/
			viewrecords: true, 
			sortorder: "asc", 
			caption:"listado de los Paises Registrados",
			ondblClickRow:function(rowid,iRow,iCol,e){
				
				var fila = jQuery(this).jqGrid('getRowData',rowid);
					
					if( jQuery("#codigo_actividades_investigacion")    ){ jQuery("#codigo_actividades_investigacion").val(fila['codigo_actividades_investigacion']); }
					if( jQuery("#nombre_actividades_investigacion") ){ jQuery("#nombre_actividades_investigacion").val(fila['nombre_actividades_investigacion']); } 
					
					
					jQuery("#dialogo_pais").dialog("close");											
       		 }
		}); 
		/*jQuery("#tablapais").jqGrid('navGrid','#pagerpais',{edit:false,add:false,del:false}); 
		jQuery("#tablapais").jqGrid('navButtonAdd','#pagerpais',{
		caption: "Columnas",
		title: "Reordena Columnas",
		onClickButton : function (){
			jQuery("#stablapais").jqGrid('columnChooser');
		
	});}*/
});
</script>