<?php echo Tag::formRemote("rubros/add", "update: mensajes", "id: fx","name: fx"); ?>

<h1>AGREGAR RUBROS</h1>

<table width="100%">
    	<tr>
    	  <th height="25" colspan="4">FORMULARIO PARA AGREGAR IES</th>
   	  </tr>
    	<tr>
    	  
    	  <th width="30%" align="right">CODIGO:</th>
    	  <td width="64%" align="left"><?php  echo Tag::textField("id","size: 50","maxlength: 50","readonly: readonly"); ?></td>
    	  
   	  </tr>
        <tr>
    	  
    	  <th width="30%" align="right">NOMBRE:</th>
    	  <td width="64%" align="left"><?php  echo Tag::textUpperField("rubro","size: 50"); ?></td>
    	  
   	  </tr>
      <tr>
    	  <td colspan="4" align="center"><button id="guardar" name="guardar">Guardar</button></td>
   	  </tr>
  </table>

<?php echo Tag::endForm(); ?>
<div id="mensajes"></div>
<?php echo view::getContent(); ?>