<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<!-- Template -->
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="en" />
	<meta name="robots" content="noindex,nofollow" />
	<title>...:::Proyecto Evolucion Snies:::....</title>
    
    <?php echo view::renderPartial('adminiziolite_encabezado'); ?>
	<?php echo view::renderPartial('javascript'); ?>
</head>

<body>
<?php echo view::renderPartial('body'); ?>
<div id="main">

	<!-- Tray -->
	<div id="tray" class="box">

		<p class="f-left box">
			Project: 
            	<font size="+1" face="verdana"> Proyecto Evolucion Snies v1.0</font>
            <br />
		</p>

		<?php if(Session::get("usuario_autenticado")==true){ ?>
        	<p class="f-right">Usuario: 
            	<strong>
            		<a href="#"><?php echo Session::get("admin_username"); ?></a>
                </strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  
                Nombre: 
                <strong>
                	<a href="#"><?php echo Session::get("nombre_completo"); ?></a>
                </strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
                <strong>
                	<a href="<?php echo core::getInstancePath(); ?>login/salir" id="logout">Cerrar Session</a>
               </strong>
            </p> 
	   <?php } ?>

	</div> <!--  /tray -->

	<hr class="noscreen" />

	<!-- Menu -->
	<!--<div id="menu" class="box">-->
	<div id="menu" class="box">
		<?php echo view::renderPartial('adminiziolite_menu'); ?>
		<!--<ul class="box f-right">
			<li><a href="#"><span><strong>Visit Site &raquo;</strong></span></a></li>
		</ul>-->
		
        <!-- Active -->
		<!--<ul class="box">
			<li id="menu-active"><a href="#"><span>Lorem ipsum</span></a></li> 
			<li><a href="#"><span>Lorem ipsum</span></a></li>
			<li><a href="#"><span>Lorem ipsum</span></a></li>
			<li><a href="#"><span>Lorem ipsum</span></a></li>
			<li><a href="#"><span>Lorem ipsum</span></a></li>
			<li><a href="#"><span>Lorem ipsum</span></a></li>
			<li><a href="#"><span>Lorem ipsum</span></a></li>
		</ul>-->

	</div> <!-- /header -->

	<hr class="noscreen" />

	<!-- Columns -->
	<div id="cols" class="box">
		<?php if(Session::get("usuario_autenticado")==true){ ?>
		<!-- Aside (Left Column) -->
		<div id="aside" class="box" >

			<div class="padding box">
				<!-- Logo (Max. width = 200px) -->
                
				<p id="logo">
                	<a href="http://www.softdesignermonteria.net">
						<?php //echo Tag::image("cabarcas_sarmiento_sas.png","border: 0","height: 80px"); ?>
                     
                        <?php //echo Tag::image("logosvarios.jpg","border: 0","height: 80px"); ?>
                    </a>
                </p>
			</div> <!-- /padding -->
			
			<?php echo view::renderPartial('adminiziolite_menu_left'); ?>
			
		</div> <!-- /aside -->
		<?php } ?>
		<hr class="noscreen" />

		<!-- Content (Right Column) -->
		<div id="content" class="box content2" style="min-height:450px;" align="center">
        	
			<div class="fix"></div>
            <div class="fix"></div>
						<?php View::getcontent(); ?>	
			<div class="fix"></div>
            <div class="fix"></div>
		</div> <!-- /content -->

	</div> <!-- /cols -->

	<hr class="noscreen" />

	<!-- Footer -->
	<div id="footer" class="box">

		<?php echo view::renderPartial('adminiziolite_pie'); ?>

	</div> <!-- /footer -->

</div> <!-- /main -->

</body>
</html>
<?php echo view::renderPartial('javascript2'); ?>