<?php echo View::getContent(); ?>


 <h1>Proyecto de Investigacion</h1>   	

<table align="center" width="100%" border="1" cellspacing="2" cellpadding="2">

 

  <tr>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("proyecto_de_investigacion/",Tag::image("aplicaciones/proyecto.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("reportes/",Tag::image("aplicaciones/reportes.png","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("flujo_de_caja/",Tag::image("aplicaciones/reportes.png","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("ies/",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

  </tr>

  <tr>

    <td height="30" align="center" valign="middle">Proyecto de Investigacion </td>

    <td height="30" align="center" valign="middle">Reportes del Sistema</td>

    <td height="30" align="center" valign="middle">Flujo de caja</td>

    <td height="30" align="center" valign="middle">Ies</td>

  </tr>

  <tr>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("objetivo_socioeconomico/",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("redes_de_cooperacion/", Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("grupos_de_investigacion/",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("centros_de_investigacion/",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

  </tr>

  <tr>

    <td height="30" align="center" valign="middle">Objetivo Socioencomico</td>

    <td height="30" align="center" valign="middle">Redes de Cooperacion</td>

    <td height="30" align="center" valign="middle">Grupos de Investigacion</td>

    <td height="30" align="center" valign="middle">Centros de Investigacion</td>

  </tr>
  
    <tr>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("productos_de_investigacion/",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("tipo_productos_de_investigacion/",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("entidades_integrantes_de_red/",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("otras_actividades/",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

  </tr>

  <tr>

    <td height="30" align="center" valign="middle">Productos De Investigacion</td>

    <td height="30" align="center" valign="middle">Tipo Productos De Investigacion</td>

    <td height="30" align="center" valign="middle">Entidades Integrantes de Red</td>

    <td height="30" align="center" valign="middle">Otras Actividades</td>

  </tr>
  
  <tr>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("nbc/",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php echo Tag::linkTo("tipo_proyecto/",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php //echo Tag::linkTo("entidades_integrantes_de_red/",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

    <td width="20%" align="center" valign="middle"><?php //echo Tag::linkTo("otras_actividades/",Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>

  </tr>

  <tr>

    <td height="30" align="center" valign="middle">NBC</td>

    <td height="30" align="center" valign="middle">Tipo Proyecto Investigacion</td>

    <td height="30" align="center" valign="middle">&nbsp;</td>

    <td height="30" align="center" valign="middle">&nbsp;</td>

  </tr>

</table>
<h1>Investigadores</h1>
<table align="center" width="100%" border="1" cellspacing="2" cellpadding="2">

  <tr>
    <td height="30" align="center" valign="middle"><?php echo Tag::linkTo("investigadores/", Tag::image("aplicaciones/clientes.png","width: 50px")); ?></td>
    <td height="30" align="center" valign="middle"><?php echo Tag::linkTo("investigadores_externos/", Tag::image("aplicaciones/clientes.png","width: 50px")); ?></td>
    <td height="30" align="center" valign="middle"><?php echo Tag::linkTo("nivel_educativo/", Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>
    <td height="30" align="center" valign="middle"><?php echo Tag::linkTo("tipo_participacion_proyecto/", Tag::image("aplicaciones/agenda.jpg","width: 50px")); ?></td>
    <td height="30" align="center" valign="middle">&nbsp;</td>
  </tr>
  <tr>

    <td height="30" align="center" valign="middle">Investigadores</td>
    
    <td height="30" align="center" valign="middle">Investigadores Externos</td>

    <td height="30" align="center" valign="middle">Nivel Educativo</td>

    <td height="30" align="center" valign="middle">Tipo Participacion Proyecto</td>

    <td height="30" align="center" valign="middle">&nbsp;</td>

  </tr>

</table>
<h1>Fuentes de Financiacion y Tipos de Gastos</h1>
<table align="center" width="100%" border="1" cellspacing="2" cellpadding="2">

  <tr>
    <td height="30" align="center" valign="middle"><?php echo Tag::linkTo("fuentes_de_financiacion_nacional/", Tag::image("aplicaciones/nacional.jpg","width: 50px")); ?></td>
    <td height="30" align="center" valign="middle"><?php echo Tag::linkTo("fuentes_de_financiacion_internacional/", Tag::image("aplicaciones/internacional.jpg","width: 50px")); ?></td>
    <td height="30" align="center" valign="middle"><?php echo Tag::linkTo("tipos_de_gastos/", Tag::image("aplicaciones/gastos.png","width: 50px")); ?></td>
    <td height="30" align="center" valign="middle">&nbsp;</td>
  </tr>
  <tr>

    <td height="30" align="center" valign="middle">Fuente de Financiacion Nacional</td>

    <td height="30" align="center" valign="middle">Fuente de Financiacion Internacional</td>

    <td height="30" align="center" valign="middle">Tipos de Gastos</td>

    <td height="30" align="center" valign="middle">&nbsp;</td>

  </tr>

</table>

<h1>Entidades territoriales</h1>
<table align="center" width="100%" border="1" cellspacing="2" cellpadding="2">

  <tr>
    <td height="30" align="center" valign="middle"><?php echo Tag::linkTo("pais/", Tag::image("aplicaciones/pais.png","width: 50px")); ?></td>
    <td height="30" align="center" valign="middle"><?php echo Tag::linkTo("departamentos/", Tag::image("aplicaciones/departamentos.JPG","width: 50px")); ?></td>
    <td height="30" align="center" valign="middle"><?php echo Tag::linkTo("municipios/", Tag::image("aplicaciones/departamentos.JPG","width: 50px")); ?></td>
    <td height="30" align="center" valign="middle"><?php echo Tag::linkTo("sector_entidad/", Tag::image("aplicaciones/departamentos.JPG","width: 50px")); ?></td>
  </tr>
  <tr>

    <td height="30" align="center" valign="middle">Pais</td>

    <td height="30" align="center" valign="middle">Departamentos</td>

    <td height="30" align="center" valign="middle">Municipios</td>

    <td height="30" align="center" valign="middle">Sector Entidad</td>

  </tr>

</table>

<h1>Administracion de Usuarios</h1>
<table align="center" width="100%" border="1" cellspacing="2" cellpadding="2">

  <tr>
    <td height="30" align="center" valign="middle"><?php echo Tag::linkTo("administrador/",Tag::image("aplicaciones/clientes.png","width: 50px")); ?></td>
    <td height="30" align="center" valign="middle"><?php echo Tag::linkTo("administrador/permisos", Tag::image("iconos/bd.png","width: 50px")); ?></td>
    <td height="30" align="center" valign="middle"><?php //echo Tag::linkTo("administrador/cambio/", Tag::image("aplicaciones/password.png","width: 50px")); ?></td>
    <td height="30" align="center" valign="middle"><?php echo Tag::linkTo("administrador/modificar/".Session::get("usuarios_id"), Tag::image("iconos/actualizar.png","width: 50px")); ?></td>
  </tr>
  <tr>

    <td height="30" align="center" valign="middle">Administrar Usuarios</td>

    <td height="30" align="center" valign="middle">Administrar Permisos</td>

    <td height="30" align="center" valign="middle"><!--Cambiar Contraseña--></td>

    <td height="30" align="center" valign="middle">Cambiar Mis Datos de Usuario</td>

  </tr>
  
  
  <tr>
    <td height="30" align="center" valign="middle"><?php echo Tag::linkTo("roles_de_usuario/",Tag::image("inicio_session.png","width: 50px")); ?></td>
    <td height="30" align="center" valign="middle"><?php //echo Tag::linkTo("departamentos/", Tag::image("aplicaciones/departamentos.jpg","width: 50px")); ?></td>
    <td height="30" align="center" valign="middle"><?php //echo Tag::linkTo("municipios/", Tag::image("aplicaciones/departamentos.jpg","width: 50px")); ?></td>
    <td height="30" align="center" valign="middle"><?php //echo Tag::linkTo("municipios/", Tag::image("aplicaciones/departamentos.jpg","width: 50px")); ?></td>
  </tr>
  <tr>

    <td height="30" align="center" valign="middle">Roles de Usuarios</td>

    <td height="30" align="center" valign="middle"></td>

    <td height="30" align="center" valign="middle"></td>

    <td height="30" align="center" valign="middle"></td>

  </tr>

</table>


