<table id="tabla<?php echo Router::getController(); ?>"></table>
<div id="pager<?php echo Router::getController(); ?>"></div>
<script>
jQuery(document).ready(function(){

		
		jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid(
		{ 
			ajaxGridOptions : {type:"POST"},
			url:'<?php echo core::getInstancePath().Router::getController(); ?>/find_detalle_buscar', 
			datatype: "json", 
			colNames:['Codigo Tipo de Gastos','Nombre Tipo de Gastos'], 
			colModel:[ 
				{ name:'codigo_tipo_de_gastos',index:'codigo_tipo_de_gastos', width:200}, 
				{ name:'nombre_tipo_de_gastos',index:'nombre_tipo_de_gastos', width:350}
			], 
			autoWidth:true,
			width: 550,
			height: 250,
			rowNum:50, 
			/*rowList:[10,20,30,40,50], */
			pager: '#pager<?php echo Router::getController(); ?>', 
			sortname: 'Cod_Tipo_Gasto', 
			/*shrinkToFit :false,*/
			viewrecords: true, 
			sortorder: "asc", 
			caption:"listado de los Tipos de Gastos Registrados",
			ondblClickRow:function(rowid,iRow,iCol,e){
				
				var fila = jQuery(this).jqGrid('getRowData',rowid);
					
					if( jQuery("#codigo_tipo_de_gastos")    ){ jQuery("#codigo_tipo_de_gastos").val(fila['codigo_tipo_de_gastos']); }
					if( jQuery("#nombre_tipo_de_gastos") ){ jQuery("#nombre_tipo_de_gastos").val(fila['nombre_tipo_de_gastos']); } 
					jQuery("#dialogo_<?php echo Router::getController(); ?>").dialog("close");											
       		 }
		}); 
		/*jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid('navGrid','#pager<?php echo Router::getController(); ?>',{edit:false,add:false,del:false}); 
		jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid('navButtonAdd','#pager<?php echo Router::getController(); ?>',{
		caption: "Columnas",
		title: "Reordena Columnas",
		onClickButton : function (){
			jQuery("#stabla<?php echo Router::getController(); ?>").jqGrid('columnChooser');
		
	});}*/
});
</script>