<?php echo View::getContent(); ?>
<br />
<br />
<?php echo Tag::form('login/valida') ?>

    <table width="600px" align="center" title="Inicio de Sesion"> 

      <thead >

        <tr>

            <th colspan="5" class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix" align="left">

            <?php echo Tag::image("iconos/clientes.png", "width: 32", "height: 32", "border: 0", "alt: Sadascol Ltda"); ?> INICIO DE SESSION            </th>

        </tr>

	</thead>

  <tbody>

    <tr>

        <td align="right">&nbsp;</td>

        <td align="left">&nbsp;</td>

    </tr>

        <tr>

          <td width="32%" align="right"><div align="right">Nombre de Usuario:</div></td>

          <td width="43%" align="left"><?php echo Tag::textField('login','size: 20') ?></td>		

        </tr>

        <tr>

          <td align="right"><div align="right">Password:</div></td>



          <td align="left"><?php echo Tag::passwordField('password','size: 20') ?></td>

        </tr>

        

        <tr>

            <th colspan="3"><button type="submit" id="inicio" name="inicio">Iniciar Sesion</button></th>

        </tr>

         <tr>

            <th colspan="3">

           			<?php echo View::getContent(); ?>

					<?php

                        foreach(View::getValidationMessages() as $message){

                            Flash::error($message->getMessage());

                        }

                    ?>            </th>

        </tr>

        </tbody>

    </table>

</div>   

<?php echo Tag::endForm(); ?>

