<?php echo Tag::formRemote(Router::getController()."/add", "update: mensajes", "id: fx","name: fx"); ?>

<h1>AGREGAR <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?></h1>

<table width="100%">
      <tr>
    	  <th height="25" colspan="4">FORMULARIO PARA AGREGAR <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?></th>
   	  </tr>
      
      <tr>
    	  
    	  <th width="30%" align="right">TIPO IDENTIFICACION <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?>:</th>
    	  <td width="64%" align="left">
		  		<?php $tp = new TipoIdentificacion();  echo Tag::select('tipo_identificacion',$tp->find(), 'using: tipo_identificacion,descripcion', 'useDummy: yes'); ?>
          </td>
    	  
   	  </tr>
      
      
    	<tr>
    	  
    	  <th width="30%" align="right">IDENTIFICACION <?php echo  strtoupper( str_replace("_"," ",Router::getController()) ); ?>:</th>
    	  <td width="64%" align="left"><?php  echo Tag::numericField("identificacion","size: 30","maxlength: 15"); ?></td>
    	  
   	  </tr>
      
      
        <tr>
    	  
    	  <th width="30%" align="right">PRIMER NOMBRE:</th>
    	  <td width="64%" align="left"><?php  echo Tag::textUpperField("primer_nombre","size: 50","maxlength: 200"); ?></td>
    	  
   	  </tr>
      <tr>
    	  
    	  <th width="30%" align="right">SEGUNDO NOMBRE:</th>
    	  <td width="64%" align="left"><?php  echo Tag::textUpperField("segundo_nombre","size: 50","maxlength: 200"); ?></td>
    	  
   	  </tr>
      <tr>
    	  
    	  <th width="30%" align="right">PRIMER APELLIDO:</th>
    	  <td width="64%" align="left"><?php  echo Tag::textUpperField("primer_apellido","size: 50","maxlength: 200"); ?></td>
    	  
   	  </tr>
      <tr>
    	  
    	  <th width="30%" align="right">SEGUNDO APELLIDO:</th>
    	  <td width="64%" align="left"><?php  echo Tag::textUpperField("segundo_apellido","size: 50","maxlength: 200"); ?></td>
    	  
   	  </tr>
      <tr>
    	  
    	  <th width="30%" align="right">CORREO</th>
    	  <td width="64%" align="left"><?php  echo Tag::textUpperField("correo","size: 50","maxlength: 200"); ?></td>
    	  
   	  </tr>
      <tr>
    	  
    	  <th width="30%" align="right">TELEFONO</th>
    	  <td width="64%" align="left"><?php  echo Tag::numericField("telefono","size: 50","maxlength: 200"); ?></td>
    	  
   	  </tr>
      <tr>
    	  
    	  <th width="30%" align="right">FAX</th>
    	  <td width="64%" align="left"><?php  echo Tag::numericField("fax","size: 50","maxlength: 200"); ?></td>
    	  
   	  </tr>
       <tr>
    	  
    	  <th width="30%" align="right">IES:</th>
    	  <td width="64%" align="left">
		  		<?php  echo Tag::textField("cod_ies","size: 10","maxlength: 200"); ?>
                <?php  echo Tag::textUpperField("nombre_ies","size: 50","maxlength: 200"); ?>
                <button id="buscar_ies" name="buscar_ies" type="button">Buscar</button>
          </td>
    	  
   	  </tr>
       <tr>
    	  
    	  <th width="30%" align="right">NBC:</th>
    	  <td width="64%" align="left">
		  		<?php  echo Tag::textField("codigo_nbc","size: 10","maxlength: 200"); ?>
                <?php  echo Tag::textUpperField("nombre_nbc","size: 50","maxlength: 200"); ?>
                <button id="buscar_nbc" name="buscar_nbc" type="button">Buscar</button>
			</td>
    	  
   	  </tr>
       <tr>
    	  
    	  <th width="30%" align="right">NIVEL EDUCATIVO:</th>
    	  <td width="64%" align="left">
		  		<?php  echo Tag::textField("codigo_nivel_educativo","size: 10","maxlength: 200"); ?>
                <?php  echo Tag::textUpperField("nombre_nivel_educativo","size: 50","maxlength: 200"); ?>
                <button id="buscar_nivel_educativo" name="buscar_nivel_educativo" type="button">Buscar</button>
			</td>
    	  
   	  </tr>
      <tr>	  
    	  <th width="30%" align="right">TIPO PARTICIPACION PROYECTO:</th>
    	  <td width="64%" align="left">
		  		<?php  echo Tag::textField("codigo_tipo_participacion_proyecto","size: 10","maxlength: 200"); ?>
                <?php  echo Tag::textUpperField("nombre_tipo_participacion_proyecto","size: 50","maxlength: 200"); ?>
                <button id="buscar_tipo_participacion_proyecto" name="buscar_tipo_participacion_proyecto" type="button">Buscar</button>
			</td>
    	  
   	  </tr>
      
  
      <tr>
    	  
    	  <th width="30%" align="right">SECTOR ENTIDAD:</th>
    	  <td width="64%" align="left">
		  	<?php  echo Tag::textField("codigo_sector_entidad","size: 10","maxlength: 50","readonly: readonly"); ?>
            <?php  echo Tag::textUpperField("nombre_sector_entidad","size: 50","maxlength: 50","readonly: readonly"); ?>
            	<button id="buscar_sector_entidad" name="buscar_sector_entidad" type="button">Buscar</button>
            </td>
    	  
   	  </tr>
      <tr>
    	  <td colspan="4" align="center"><button id="guardar" name="guardar">Guardar</button></td>
   	  </tr>
  </table>

<?php echo Tag::endForm(); ?>
<div id="mensajes"></div>
<?php echo view::getContent(); ?>

<script>
jQuery(document).ready(function(e) {
        jQuery("#cod_ies").attr("readOnly","ReadOnly");
		jQuery("#nombre_ies").attr("readOnly","ReadOnly");
		jQuery("#codigo_nbc").attr("readOnly","ReadOnly");
		jQuery("#nombre_nbc").attr("readOnly","ReadOnly");
		jQuery("#codigo_nivel_educativo").attr("readOnly","ReadOnly");
		jQuery("#nombre_nivel_educativo").attr("readOnly","ReadOnly");
		jQuery("#codigo_tipo_participacion_proyecto").attr("readOnly","ReadOnly");
		jQuery("#nombre_tipo_participacion_proyecto").attr("readOnly","ReadOnly");
});
</script>