<?php 
	if(isset($_REQUEST["opcion"])){
		Flash::notice("Doble Click en la Fila para ".$_REQUEST["opcion"]); 
	}
?>
<table id="tabla<?php echo Router::getController(); ?>"></table>
<div id="pager<?php echo Router::getController(); ?>"></div>
<script>
jQuery(document).ready(function(){

		
		jQuery("#tabla<?php echo Router::getController(); ?>").jqGrid(
		{ 
			ajaxGridOptions : {type:"POST"},
			url:'<?php echo core::getInstancePath().Router::getController(); ?>/find_detalle_buscar', 
			datatype: "json", 
			colNames:['Idetificacion','Primer nombre','Segundo nombre','Primer Apellido','Segundo Apellido'], 
			colModel:[ 
				{ name:'identificacion',index:'Identificacion_Externo', width:150}, 
				{ name:'primer_nombre',index:'PrimerNombre', width:150},
				{ name:'segundo_nombre',index:'SegundoNombre', width:150}, 
				{ name:'primer_apellido',index:'PrimerApellido', width:150},
				{ name:'segundo_apellido',index:'SegundoApellido', width:150}
			], 
			autoWidth:true,
			width: 550,
			height: 250,
			rowNum:50, 
			/*rowList:[10,20,30,40,50], */
			pager: '#pager<?php echo Router::getController(); ?>', 
			sortname: 'Identificacion_Externo', 
			/*shrinkToFit :false,*/
			viewrecords: true, 
			sortorder: "asc", 
			caption:"listado de los Investigadores Registrados",
			ondblClickRow:function(rowid,iRow,iCol,e){
				
				var fila = jQuery(this).jqGrid('getRowData',rowid);
					
					
					if( jQuery("#codigo_investigador")    ){ jQuery("#codigo_investigador").val(fila['identificacion']); }
					if( jQuery("#nombre_investigador")    ){ jQuery("#nombre_investigador").val(fila['primer_nombre'] + ' ' + fila['segundo_nombre'] + ' ' + fila['primer_apellido'] + ' ' + fila['segundo_apellido']); } 
				
					<?php if(isset($_REQUEST["opcion"]) ){ ?>
						redireccionar_action("<?php echo Router::getController(); ?>/<?php echo $_REQUEST["opcion"]; ?>/" + fila['identificacion'] );
					<?php }else{?>	
						jQuery("#dialogo_<?php echo Router::getController(); ?>").dialog("close");
					<?php } ?>
					
       		 }
		}); 
		/*jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('navGrid','#pager<?php //echo Router::getController(); ?>',{edit:false,add:false,del:false}); 
		jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('navButtonAdd','#pager<?php //echo Router::getController(); ?>',{
		caption: "Columnas",
		title: "Reordena Columnas",
		onClickButton : function (){
			jQuery("#tabla<?php //echo Router::getController(); ?>").jqGrid('columnChooser');
		
	});}*/
});
</script>