<?php echo view::getContent(); ?>

<table width="400px" cellpadding="2" cellspacing="2" class="ui-widget ui-widget-content ui-corner-all ui-dialog-titlebar ui-widget-header ui-helper-clearfix ui-front">

    	<tr>

        	<td align="center"><?php echo Tag::linkTo(Router::getController()."/agregar",Tag::image("aplicaciones/agregar.jpg","width: 50px")); ?></td>
			<td align="center"><?php echo Tag::linkTo(Router::getController()."/buscar",Tag::image("aplicaciones/buscar.jpg","width: 50px")); ?></td>
            <td align="center"><?php echo Tag::linkTo(Router::getController()."/buscar/?opcion=modificar",Tag::image("iconos/entrar.png","width: 50px")); ?></td>
			<td align="center"><?php echo Tag::linkTo(Router::getController()."/buscar/?opcion=eliminar",Tag::image("iconos/inicio.png","width: 50px")); ?></td>

        </tr>

        <tr>

        	<td align="center">Agregar</td>
			<td align="center">Listar Todas</td>
			<td align="center">Modificar</td>
            <td align="center">Eliminar</td>

        </tr>

    </table>
    
