<table id="tablapais"></table>
<div id="pagerpais"></div>
<script>
jQuery(document).ready(function(){

		
		jQuery("#tablapais").jqGrid(
		{ 
			ajaxGridOptions : {type:"POST"},
			url:'<?php echo core::getInstancePath().Router::getController(); ?>/find_detalle_buscar', 
			datatype: "json", 
			colNames:['Codigo Pais','Nombre Pais'], 
			colModel:[ 
				{ name:'codigo_pais',index:'codigo_pais', width:200}, 
				{ name:'nombre_pais',index:'nombre_pais', width:350}
			], 
			autoWidth:true,
			width: 550,
			height: 250,
			rowNum:50, 
			/*rowList:[10,20,30,40,50], */
			pager: '#pagerpais', 
			sortname: 'Cod_Pais', 
			/*shrinkToFit :false,*/
			viewrecords: true, 
			sortorder: "asc", 
			caption:"listado de los Paises Registrados",
			ondblClickRow:function(rowid,iRow,iCol,e){
				
				var fila = jQuery(this).jqGrid('getRowData',rowid);
					
					if( jQuery("#codigo_pais")    ){ jQuery("#codigo_pais").val(fila['codigo_pais']); }
					if( jQuery("#nombre_pais") ){ jQuery("#nombre_pais").val(fila['nombre_pais']); } 
					
					if( jQuery("#codigo_departamentos") ){ jQuery("#codigo_departamentos").val(""); }
					if( jQuery("#nombre_departamentos") ){ jQuery("#nombre_departamentos").val(""); } 
					
					if( jQuery("#codigo_municipios") ){ jQuery("#codigo_municipios").val(""); }
					if( jQuery("#nombre_municipios") ){ jQuery("#nombre_municipios").val(""); } 
					
					if( jQuery("#codigo_sector_entidad") ){ jQuery("#codigo_sector_entidad").val(""); }
					if( jQuery("#nombre_sector_entidad") ){ jQuery("#nombre_sector_entidad").val(""); } 
					
					
					
					jQuery("#dialogo_pais").dialog("close");											
       		 }
		}); 
		/*jQuery("#tablapais").jqGrid('navGrid','#pagerpais',{edit:false,add:false,del:false}); 
		jQuery("#tablapais").jqGrid('navButtonAdd','#pagerpais',{
		caption: "Columnas",
		title: "Reordena Columnas",
		onClickButton : function (){
			jQuery("#stablapais").jqGrid('columnChooser');
		
	});}*/
});
</script>