<?php foreach($admin as $usuario): ?>
<table border="0" cellpadding="1" width="90%">
    <tr>
   	 <th scope="col">USUARIO AGREGADO</th>
   	 <th scope="col">&nbsp;</th>
    </tr>
  <tr>
    <td width="50%" height="30" ><div align="right">Nombre Usuario</div></td>
    <td width="50%" scope="col"><?php echo $usuario->username; ?></td>
    </tr>
  <tr>
    <td height="30"><div align="right"><strong>Clave</strong></div></td>
    <td height="30"><?php echo Tag::PasswordField("password", "size: 15","maxlength: 20","value: $usuario->password","readonly: true") ?><br/>Nota: La clave no se visualiza por motivos de seguridad</td>
    </tr>
  <tr>
    <td height="30"><div align="right">Nombre Completo</div></td>
    <td height="30"><?php echo $usuario->nombre_completo; ?></td>
    </tr>
  <tr>
    <td height="30"><div align="right"><strong>Tipo de Usuario</strong></div></td>
    <td height="30"><?php $rol = new Roles();
		    $tipo_usuario = $rol->findFirst("id = '$usuario->tipo_usuario'"); 
		    echo $tipo_usuario->descripcion; ?></td>
    </tr>
  <tr>
    <td height="30"></td>    
    <td height="30"><div align="center"><?php echo Tag::linkTo("administrador/modificar/$usuario->id", Tag::image("/iconos/editar.png")) ?></div></td>    
  </tr>
</table>
<?php endforeach; ?>

<?php echo View::getContent(); ?>